let cards = [
  //  Add your card in this section
  //  Follow this example format:
  //  ["Art Name", "Page URL", "Image URL", "Your Name", "Your Github Link"],
  [
    "spinning-squares",
    "./Art/gheezl/index.html",
    "./Art/gheezl/spinning-squares.gif",
    "gheezl",
    "https://github.com/gheezl",
  ],
  [
    "BINGNAN-CHEN",
    "./Art/BINGNAN-CHEN/index.html",
    "./Art/BINGNAN-CHEN/box.jpg",
    "BINGNAN-CHEN",
    "https://github.com/r1991108",
  ],
  [
    "cool-jengwa",
    "./Art/cool-jengwa/index.html",
    "./Art/cool-jengwa/melon-cuts.PNG",
    "jengwa",
    "https://github.com/Jengwa",
  ],
  [
    "cute bear",
    "./Art/carlacentenor/index.html",
    "./Art/carlacentenor/bear.JPG",
    "carlacentenor",
    "https://github.com/carlacentenor",
  ],
  [
    "koala",
    "./Art/fuckupc/index.html",
    "./Art/fuckupc/icon.PNG",
    "fuckupc",
    "https://github.com/fuckupc",
  ],
  [
    "Shy Rabbit",
    "./Art/teits/index.html",
    "./Art/teits/preview.png",
    "Teits",
    "https://github.com/teitss",
  ],
  [
    "Pikachu",
    "./Art/julesdowork/index.html",
    "./Art/julesdowork/pikachu.png",
    "Julesdowork",
    "https://github.com/Julesdowork",
  ],
  [
    "CSS Ace",
    "./Art/TinatheAce/ace.html",
    "./Art/TinatheAce/ace.png",
    "Tina the Ace",
    "https://github.com/nnh242",
  ],
  [
    "Frank",
    "./Art/AndrewDiedrich/index.html",
    "./Art/AndrewDiedrich/Frank.PNG",
    "Andrew Diedrich",
    "https://github.com/AndrewDiedrich",
  ],
  [
    "CSS Dog",
    "./Art/Dog/index.html",
    "./Art/Dog/dog.gif",
    "Chintu Yadav Sara",
    "https://github.com/chintuyadav",
  ],
  [
    "No Face",
    "./Art/saamiyah/no-face.html",
    "./Art/saamiyah/no-face.gif",
    "Saamiyah",
    "https://github.com/Saamiyah",
  ],
  [
    "Mahatma Gandhi",
    "./Art/Mahatma%20Gandhi/index.html",
    "./Art/Mahatma%20Gandhi/Gandhi.png",
    "Chintu Yadav Sara",
    "https://github.com/chintuyadav",
  ],
  [
    "WindMill Animation",
    "./Art/WindMill/index.html",
    "./Art/WindMill/windmill.gif",
    "Chintu Yadav Sara",
    "https://github.com/chintuyadav",
  ],
  [
    "CSS Bird",
    "./Art/Bird/index.html",
    "./Art/Bird/Bird.png",
    "Chintu Yadav Sara",
    "https://github.com/chintuyadav",
  ],
  [
    "Robot friend",
    "./Art/joy/robot.html",
    "./Art/joy/robot.png",
    "Joy",
    "https://github.com/royranger",
  ],
  [
    "Spookiest fr̶iend",
    "./Art/pavel/spooky.html",
    "./Art/pavel/spooky.png",
    "Pavel",
    "https://github.com/pavelisp",
  ],
  [
    "Hamburger",
    "./Art/Aszmel/Hamburger.html",
    "./Art/Aszmel/hamburger.png",
    "Aszmel",
    "https://github.com/Aszmel",
  ],
  [
    "Polish Flag animation",
    "./Art/kris/kris.html",
    "./Art/kris/kris.png",
    "Kris",
    "https://github.com/krzysiekh",
  ],
  [
    "Frog",
    "./Art/TheMicroGirl/frog.html",
    "./Art/TheMicroGirl/frog.PNG",
    "TheMicroGirl",
    "https://github.com/TheMicroGirl",
  ],
  [
    "8-bit style Link",
    "./fischbot/index.html",
    "./Art/fischbot/link.png",
    "Fischbot",
    "https://github.com/fischbot",
  ],
  [
    "Ghost Animation",
    "./Art/ghost/ghost.html",
    "./Art/ghost/ghost.png",
    "Jhonattan",
    "https://github.com/jhonattanbenitez",
  ],
  [
    "Boo",
    "./Art/zach-caldwell/ghost.html",
    "./Art/zach-caldwell/ghost.PNG",
    "Zach",
    "https://github.com/zach-caldwell",
  ],
  [
    "Pumpkin",
    "./Art/Asam/pumpkin.html",
    "./Art/Asam/pumpkin.png",
    "Asam",
    "https://github.com/shan5742",
  ],
  [
    "Funky Pumpkin",
    "./Art/Matt/pumpkin.html",
    "./Art/Matt/icon.PNG",
    "Matt",
    "https://github.com/mattcsmith",
  ],
  [
    "Spooky Androids!",
    "./Art/hmahajan/androids.html",
    "./Art/hmahajan/androids.JPG",
    "hmahajan",
    "https://github.com/hmahajan99",
  ],
  [
    "TrailSnail",
    "./Art/trailsnail/spinner.html",
    "./Art/trailsnail/spinner.png",
    "Complex Spinner",
    "https://github.com/trailsnail",
  ],
  [
    "Spooky Penguine",
    "./Art/Shruti/penguine.html",
    "./Art/Shruti/penguine.PNG",
    "Shruti",
    "https://github.com/shruti49",
  ],
  [
    "Pac-Man Run",
    "./Art/PaulC/pacman_run.html",
    "./Art/PaulC/pac.png",
    "PaulC",
    "https://github.com/m2paulc",
  ],
  [
    "Frankenstein",
    "./Art/josh/frankie.html",
    "./Art/josh/Capture.PNG",
    "Josh",
    "https://github.com/jcothard",
  ],
  [
    "Koala Head",
    "./Art/Are/index.html",
    "./Art/Are/koala.png",
    "Are",
    "https://github.com/Ar3Tea",
  ],
  [
    "CSS Loader",
    "./Art/Frozenfroggie/index.html",
    "./Art/Frozenfroggie/loader.gif",
    "Frozenfroggie",
    "https://github.com/frozenfroggie",
  ],
  [
    "Macho Ghost",
    "./Art/Astro/index.html",
    "./Art/Astro/ghost.jpeg",
    "Amy",
    "https://github.com/astrokwk",
  ],
  [
    "Pumpkin",
    "./Art/katcode/index.html",
    "./Art/katcode/pumpkin.png",
    "katcode",
    "https://github.com/katcode",
  ],
  [
    "Javascript Coffee Cu",
    "./Art/JS Coffee Cup/js_coffee_cup.html",
    "./Art/JS Coffee Cup/js_coffee_cup.gif",
    "Bilal Younso",
    "https://github.com/bilalyounso",
  ],
  [
    "CSS Clock",
    "./Art/Sean-Dees/sean.html",
    "./Art/Sean-Dees/clock.PNG",
    "Sean Dees",
    "https://github.com/sdees82",
  ],
  [
    "Linux",
    "./Art/linux/index.html",
    "./Art/linux/linux.gif",
    "Thea",
    "https://github.com/highflyer910",
  ],
  [
    "Devices",
    "./Art/virtual/index.html",
    "./Art/virtual/virtual.png",
    "Virtual",
    "https://github.com/virtual",
  ],
  [
    "Owl",
    "./Art/owl/owl.html",
    "./Art/owl/owl.png",
    "Thea",
    "https://github.com/highflyer910",
  ],
  [
    "Sunrise and Sunset",
    "./Art/sanjithpk/index.html",
    "./Art/sanjithpk/sun.png",
    "Sanjith",
    "https://github.com/sanjithpk",
  ],
  [
    "Halloween Cat",
    "./Art/Martyav/halloween_cat.html",
    "./Art/Martyav/halloween_cat.png",
    "Martyav",
    "https://github.com/martyav",
  ],
  [
    "Pumpkin",
    "./Art/pohyi-k/index.html",
    "./Art/pohyi-k/pumkin.png",
    "pohyi-k",
    "https://github.com/pohyi-k",
  ],
  [
    "8bit-Pumpkin",
    "./Art/8bit-pumpkin/index.html",
    "./Art/8bit-pumpkin/8bit-Pumpkin.png",
    "MatthewS",
    "https://github.com/MatthewStoddart",
  ],
  [
    "Catrina",
    "./Art/catrina/index.html",
    "./Art/catrina/catrina.png",
    "Tahi",
    "https://github.com/cTahirih",
  ],
  [
    "Run to Win",
    "./Art/run to win/index.html",
    "./Art/run to win/my.png",
    "Sanidhya",
    "https://github.com/sanidhya2000",
  ],
  [
    "Hallucinations",
    "./Art/kahwaii/kahwaii.html",
    "./Art/kahwaii/dizzy.PNG",
    "kahwaii",
    "https://github.com/kahwaii",
  ],
  [
    "CSS Clock",
    "./Art/KwanwooJeong/index.html",
    "./Art/KwanwooJeong/css-clock.png",
    "Kwanwoo Jeong",
    "https://github.com/kwanwooi25",
  ],
  [
    "Bear",
    "./Art/MAG/bear.html",
    "./Art/MAG/bear.png",
    "gettaplay",
    "https://github.com/gettaplay",
  ],
  [
    "SPOOKY FAMILY",
    "./Art/Anca/index.html",
    "./Art/Anca/family.png",
    "Anca",
    "https://github.com/AncaWebDev",
  ],
  [
    "Heart",
    "./Art/mamta/heart.html",
    "./Art/mamta/heart.png",
    "palmamta",
    "https://github.com/palmamta",
  ],
  [
    "The Grim Reaper",
    "./Art/OhSnapdragon/reaper.html",
    "./Art/OhSnapdragon/reaper.PNG",
    "OhSnapdragon",
    "https://github.com/OhSnapdragon",
  ],
  [
    "Flying Bird",
    "./Art/mamta/index2.html",
    "./Art/mamta/flying.png",
    "palmamta",
    "https://github.com/palmamta",
  ],
  [
    "Creepy Selfie",
    "./Art/Creepy Selfie/index.html",
    "./Art/Creepy Selfie/CreepySelfie.png",
    "bronasek",
    "https://github.com/bronasek",
  ],
  [
    "Redvan's Apple",
    "./Art/redvan/index.html",
    "./Art/redvan/redvansApple.jpg",
    "Redvanisation",
    "https://github.com/Redvanisation",
  ],
  [
    "Heart",
    "./Art/Heart/index.html",
    "./Art/Heart/heart.gif",
    "SliceOLife",
    "https://github.com/SliceOLife",
  ],
  [
    "Hamburger",
    "./Art/Nikhil/index.html",
    "./Art/Nikhil/hamburger.png",
    "Nikhil Shrivastava",
    "https://github.com/NikhilShrivastava",
  ],
  [
    "Arc Reactor",
    "./Art/AhmedH14/index.html",
    "./Art/AhmedH14/ScreenShot.png",
    "Ahmed Hajat",
    "https://github.com/AhmedH14",
  ],
  [
    "Pixel Charizard",
    "./Art/mctrl/index.html",
    "./Art/mctrl/charizard.jpg",
    "Martina",
    "https://github.com/mctrl",
  ],
  [
    "Funky Monkey",
    "./Art/andra/index.html",
    "./Art/andra/andra.png",
    "Andra",
    "https://github.com/andrapetronela",
  ],
  [
    "Kirby",
    ".Art/Kirby.index.html",
    "./Art/Kirby/Kirby.png",
    "Aldiekmann",
    "https://github.com/aldiekmann",
  ],
  [
    "Cartoon Skull",
    "./Art/Jose-Rios/index.html",
    "./Art/Jose-Rios/skull_css.JPG",
    "Jose",
    "https://github.com/Riosjl41",
  ],
  [
    "Butterfly",
    "./Art/R-Butterfly/index.html",
    "./Art/R-Butterfly/R-Butterfly.png",
    "Russell",
    "https://github.com/russellsoppe",
  ],
  [
    "Robo - Dancer",
    "./Art/Florin/index.html",
    "./Art/Florin/robo-dancer.png",
    "Florin",
    "https://github.com/LoposFlorin",
  ],
  [
    "Smiley",
    "./Art/adrianomi/index.html",
    "./Art/adrianomi/smiley.jpg",
    "adrianomi",
    "https://github.com/adrianomi",
  ],
  [
    "Watermelon",
    "./Art/watermelon/index.html",
    "./Art/watermelon/watermelon-screenshot.PNG",
    "Dan Horsch",
    "https://github.com/danhorsch",
  ],
  [
    "Beach",
    "./Art/sdfnz/beach.html",
    "./Art/sdfnz/beach.jpg",
    "sdfnz",
    "https://github.com/sdfnz",
  ],
  [
    "Funny Avocado",
    "./Art/yokesharun/index.html",
    "./Art/yokesharun/avocado.png",
    "yokesharun",
    "https://github.com/yokesharun",
  ],
  [
    "Gameboy",
    "./Art/mctrl/gameboy.html",
    "./Art/mctrl/gameboy.jpg",
    "Martina",
    "https://github.com/mctrl",
  ],
  [
    "Frog",
    "./Art/Elin-frog/index.html",
    "./Art/Elin-frog/frog.png",
    "elindjuren",
    "https://github.com/elindjuren",
  ],
  [
    "Fita Cassete",
    "./Art/Pliavi/index.html",
    "./Art/Pliavi/print.png",
    'Vitor "Pliavi" Silvério',
    "https://github.com/Pliavi",
  ],
  [
    "Panda",
    "./Art/Madhuri/index.html",
    "./Art/Madhuri/Screenshot.png",
    "Madhuri Soni",
    "https://github.com/sonimadhuri",
  ],
  [
    "Xmas",
    "./Art/Chrissy/xmas.html",
    "./Art/Chrissy/xmas.png",
    "Chrissy",
    "https://github.com/charlecoda88",
  ],
  [
    "Spooky violin",
    "./Art/JaniH92/index.html",
    "./Art/JaniH92/spookyViolin.GIF",
    "Jani Hänninen",
    "https://github.com/jh1992jh",
  ],
  [
    "Responsive Bars",
    "./Art/Rahul/index.html",
    "./Art/Rahul/index.png",
    "Rahul",
    "https://github.com/rik-96",
  ],
  [
    "Creepy Pumpkin",
    "./Art/Virtual1/Virtual1.html",
    "./Art/Virtual1/Virtual1.bmp",
    "Jessica Erasmus",
    "https://github.com/Virtual1",
  ],
  [
    "Boat",
    "./Art/Boat/index.html",
    "./Art/Boat/Boat.png",
    "Titi Arimba",
    "https://github.com/titiarimba",
  ],
  [
    "Koala",
    "./Art/Chrissy/koala.html",
    "./Art/Chrissy/koalaedit.png",
    "Chrissy",
    "https://github.com/charlecoda88",
  ],
  [
    "Landscape",
    "./Art/David/index.html",
    "./Art/David/landscape.png",
    "The24thDS",
    "https://github.com/the24thds",
  ],
  [
    "Birthday Balloon",
    "./Art/Dazzla2020/index.html",
    "./Art/Dazzla2020/bithday-balloon.png",
    "Dazzla",
    "https://github.com/Dazzla2020",
  ],
  [
    "Spinning Shuriken",
    "./Art/Mr.Zilox/index.html",
    "./Art/Mr.Zilox/ninga.png",
    "Mr.Zilox",
    "https://github.com/mitchellKalcher/",
  ],
  [
    "Sunny apple",
    "./Art/DepSteph/my-art.html",
    "./Art/DepSteph/my-art.png",
    "DepSteph",
    "https://github.com/StephDs",
  ],
  [
    "Airplane",
    "./Art/jen/plane.html",
    "./Art/jen/plane.png",
    "Jen",
    "https://github.com/jenwr",
  ],
  [
    "Mouse",
    "./Art/jen/mouse.html",
    "./Art/jen/mouse.png",
    "Jen",
    "https://github.com/jenwr",
  ],
  [
    "Hungry Caterpillar",
    "./Art/CarmenIancu/index.html",
    "./Art/CarmenIancu/hungry_caterpillar.JPG",
    "CarmenIancu",
    "https://github.com/CarmenIancu",
  ],
  [
    "CSS Flower",
    "./Art/Kim/index.html",
    "./Art/Kim/Flower.png",
    "Kim",
    "https://github.com/QAMinn2468",
  ],
  [
    "Mario Pipe",
    "./Art/iggyzane/index.html",
    "./Art/iggyzane/MarioPipe.PNG",
    "Iggy Baker",
    "https://github.com/iggyzane",
  ],
  [
    "Pizza",
    "./Art/carter/pizza.html",
    "./Art/carter/pizza.png",
    "Carter",
    "https://github.com/carterschieffer",
  ],
  [
    "Rocket",
    "./Art/cbh6/rocket.html",
    "./Art/cbh6/rocket.jpg",
    "Cristian",
    "https://github.com/cbh6",
  ],
  [
    "Space Invader",
    "./Art/JFox/spaceInvader.html",
    "./Art/JFox/spaceInvader.png",
    "Jeremy Fox",
    "https://github.com/jeremyfox36",
  ],
  [
    "Cactus in a Pot",
    "./Art/danIancuV/index.html",
    "./Art/danIancuV/CactusInAPot.jpg",
    "danIancuV",
    "https://github.com/danIancuV",
  ],
  [
    "Beating Heart",
    "./Art/nikiya/index.html",
    "./Art/nikiya/heart-beat.png",
    "Nikiya Simpson",
    "https://github.com/nikiyasimpson",
  ],
  [
    "Waving Penguin",
    "./Art/orinayo/index.html",
    "./Art/orinayo/penguin_art.png",
    "Orinayo Oyelade",
    "https://github.com/orinayo",
  ],
  [
    "Taco Animation",
    "./Art/roninmittal/index.html",
    "./Art/roninmittal/taco.png",
    "Ronin Mittal",
    "https://github.com/roninmittal",
  ],
  [
    "Ghost",
    "./Art/toserjude/ghost.html",
    "./Art/toserjude/ghost.jpg",
    "toserjude",
    "https://github.com/toserjude",
  ],
  [
    "JS Logo",
    "./Art/Thulasi/index.html",
    "./Art/Thulasi/js-logo.PNG",
    "ThulasiA",
    "https://github.com/ThulasiA",
  ],
  [
    "Black Cat",
    "./Art/toserjude/blackCat.html",
    "./Art/toserjude/cat.jpg",
    "toserjude",
    "https://github.com/toserjude",
  ],
  [
    "Minimalist Hover and Move Away",
    "./Art/JoyceMinimalistArt/index.html",
    "./Art/JoyceMinimalistArt/joycemini.png",
    "Joyce Wambui",
    "https://github.com/joycewambui",
  ],
  [
    "Baymax",
    "./Art/dziukers/index.html",
    "./Art/dziukers/Baymax.JPG",
    "dziukers",
    "https://github.com/dziukers",
  ],
  [
    "Smart Phone",
    "./Art/chathurasam/smartphone.html",
    "./Art/chathurasam/screenshot.png",
    "Chathura Samarajeewa",
    "https://github.com/ChathuraSam",
  ],
  [
    "Pikachu",
    "./Art/Sherin/pikachu.html",
    "./Art/Sherin/pikachu.png",
    "Sherin Binu",
    "https://github.com/SherOnDale",
  ],
  [
    "Fox",
    "./Art/Platy/index.html",
    "./Art/Platy/fox.png",
    "Atti",
    "https://github.com/Platyka",
  ],
  [
    "Just alone panda",
    "./Art/justpanda/index.html",
    "./Art/justpanda/panda.PNG",
    "Maximsan",
    "https://github.com/maximsan",
  ],
  [
    "Squirtle",
    "./Art/Sherin/squirtle.html",
    "./Art/Sherin/squirtle.png",
    "Sherin Binu",
    "https://github.com/SherOnDale",
  ],
  [
    "Butterfree",
    "./Art/Sherin/butterfree.html",
    "./Art/Sherin/butterfree.png",
    "Sherin Binu",
    "https://github.com/SherOnDale",
  ],
  [
    "Captain's Shield",
    "./Art/napvlm/shield.html",
    "./Art/napvlm/shield.png",
    "Ruslan Anisimov",
    "https://github.com/napvlm",
  ],
  [
    "Happy Emoji",
    "./Art/uhayon/emoji.html",
    "./Art/uhayon/emoji.png",
    "Uri",
    "https://github.com/uhayon",
  ],
  [
    "Electrode",
    "./Art/Sherin/electrode.html",
    "./Art/Sherin/electrode.png",
    "Sherin Binu",
    "https://github.com/SherOnDale",
  ],
  [
    "Mounion vaakuna",
    "./Art/MAhoMaha12112017/MAhoMaha12112017.html",
    "./Art/MAhoMaha12112017/mouniovaakuna_pieni_skaalattu.png",
    "MAho",
    "https://github.com/MAhoMaha12112017",
  ],
  [
    "bouncing ball",
    "./Art/jaeja/index.html",
    "./Art/jaeja/ball.png",
    "jae",
    "https://github.com/jaeja",
  ],
  [
    "Egg",
    "./Art/tomikonio/egg.html",
    "./Art/tomikonio/egg.png",
    "tomikonio",
    "https://github.com/tomikonio",
  ],
  [
    "Shaky Wall",
    "./Art/tsrumia/index.html",
    "./Art/tsrumia/image.jpg",
    "Tsrumia",
    "https://github.com/mukherj",
  ],
  [
    "Birthday cake",
    "./Art/KarinPR/index.html",
    "./Art/KarinPR/Birthday_cake.png",
    "Karin Povolozki-Rabichev",
    "https://github.com/KarinPR",
  ],
  [
    "Skype logo",
    "./Art/ddoyediran/index12.html",
    "./Art/ddoyediran/Skype-logo.jpg",
    "Damilare Oyediran",
    "https://github.com/ddoyediran",
  ],
  [
    "The Minimal Artist",
    "./Art/Arpit Jain/Arpit Jain.html",
    "./Art/Arpit Jain/Arpit Jain.png",
    "Arpit Jain",
    "https://github.com/arpitjainds",
  ],
  [
    "Minimal Clown",
    "./Art/Jithendra Yenugula/jithendrabsy.html",
    "./Art/Jithendra Yenugula/jithendrabsy.png",
    "Jithendra Yenugula",
    "https://github.com/jithendrabsy",
  ],
  [
    "Square Fox",
    "./Art/Fox/index.html",
    "./Art/Fox/fox.png",
    "Bruno Bolting",
    "https://github.com/brunobolting",
  ],
  [
    "Cub",
    "./Art/matheusagcosta/index.html",
    "./Art/matheusagcosta/cub.png",
    "matheusagcosta",
    "https://github.com/matheusagcosta",
  ],
  [
    "Airpods",
    "./Art/KatrinaRose14/index.html",
    "./Art/KatrinaRose14/airpods.png",
    "Katrina Rose Yates",
    "https://github.com/KatrinaRose14",
  ],
  [
    "Lambda",
    "./Art/felipp/index.html",
    "./Art/felipp/lambda.png",
    "felipp",
    "https://github.com/skelrilod",
  ],
  [
    "Ringing bell",
    "./Art/RedSquirrrel/index.html",
    "./Art/RedSquirrrel/ringing bell.png",
    "Anette",
    "https://github.com/RedSquirrrel",
  ],
  [
    "animated-face",
    "./Art/Saksham/index.html",
    "./Art/Saksham/animated-face.png",
    "Saksham Singh",
    "https://github.com/Saksham27",
  ],
  [
    "Animated Circle",
    "./Art/Sravya/index.html",
    "./Art/Sravya/index.png",
    "Sravya Challa",
    "https://github.com/sravya-challa-au3",
  ],
  [
    "Turn Around",
    "./Art/Hila/index.html",
    "./Art/Hila/animation_Gif.gif",
    "Hila Ailon",
    "https://github.com/Hila-Ailon",
  ],
  [
    "Christmas Tree",
    "./Art/Ablutie/index.html",
    "./Art/Ablutie/christmasTree.jpg",
    "Mihai Dragomir",
    "https://github.com/Ablutie",
  ],
  [
    "AtariNTSCColors",
    "./Art/GiantsCode/index.html",
    "./Art/GiantsCode/AtariNTSCColors.gif",
    "Daniel Macleod GiantsCode",
    "https://github.com/giantscode",
  ],
  [
    "Heart Animation",
    "./Art/RenaOnFire/index.html",
    "./Art/RenaOnFire/HeartImage.png",
    "Rena OnFire",
    "https://github.com/renaonfire",
  ],
  [
    "Anonymus Animation",
    "/Art/Anonymus/anonymus.html",
    "/Art/Anonymus/9mi2FINz_400x400.jpg",
    "Hope somebody will find this funny",
    "https://github.com/Jurek33",
  ],
  [
    "Rolling circle animation",
    "/Art/Kenneth/index.html",
    "Art/Kenneth/rolling_circle.jpg",
    "Kenneth Skodje",
    "https://github.com/KSkodje",
  ],
  [
    "Pokeball",
    "./Art/AdityaSaroj/index.html",
    "./Art/AdityaSaroj/pokeball.png",
    "Aditya Kumar Saroj",
    "https://github.com/AdityaSaroj",
  ],
  [
    "Forest Racer",
    "./Art/rainoverme002/index.html",
    "./Art/rainoverme002/forest-racer.png",
    "rainoverme002",
    "https://github.com/rainoverme002",
  ],
  [
    "Drop",
    "./Art/ikaem/index.html",
    "./Art/ikaem/drop.gif",
    "ikaem",
    "https://github.com/ikaem",
  ],
  [
    "Drop",
    "./Art/Wow/index.html",
    "./Art/Wow/wow.gif",
    "sagihill",
    "https://github.com/sagihill",
  ],
  [
    "Rotate",
    "./Art/Abio/index.html",
    "./Art/Abio/Screenshot.png",
    "abiola-ajibola",
    "https://github.com/abiola-ajibola",
  ],
  [
    "Gangnam",
    "./Art/Gangnam/index.html",
    "./Art/Gangnam/gangnam.png",
    "Ibrahim Tarabay",
    "https://github.com/IbrahimTarabay",
  ],
  [
    "CSS Cube Perspective",
    "./Art/carljustineoyales/index.html",
    "./Art/carljustineoyales/CSSCubePerspective.gif",
    "Carl Justine Oyales",
    "https://github.com/carljustineoyales",
  ],
  [
    "Strange Ball",
    "./Art/ronchito13/index.html",
    // "./Art/ronchito13/ball.gif",
    "", // no artwork in folder
    "Ronchito13",
    "https://github.com/Ronchito13",
  ],
  [
    "Art-E-opera",
    "./Art/mayIGit_meg/index.html",
    "./Art/mayIGit_meg/cover2.gif",
    "mayIGit",
    "https://github.com/mayIGit",
  ],
  [
    "CSS Mosaic Layout",
    "./Art/mosaic-layout/index.html",
    "./Art/mosaic-layout/mosaic.png",
    "collinsmuriuki",
    "https://github.com/collinsmuriuki",
  ],
  [
    "Smiling Clown",
    "./Art/VelizarStavrev/index.html",
    "./Art/VelizarStavrev/smilingClown.png",
    "VelizarStavrev",
    "https://github.com/VelizarStavrev",
  ],
  [
    "Fishes",
    "./Art/Fishes/index.html",
    "./Art/Fishes/fishes.png",
    "Konstantin Dergachev",
    "https://github.com/konstantindergachev",
  ],
  [
    "Animate The Button",
    "./Art/krishan93985/index.html",
    "./Art/krishan93985/animation.png",
    "krishan93985",
    "https://github.com/krishan93985",
  ],
  [
    "Cosmos",
    "./Art/prajwal-mendon/index.html",
    "./Art/prajwal-mendon/cosmos.png",
    "Prajwal Mendon",
    "https://github.com/Prajwal-mendon",
  ],
  [
    "My not-so Flashy Animation",
    "./Art/SonalJain/index.html",
    "./Art/SonalJain/My not-so Flashy Animation.gif",
    "Sonal Jain",
    "https://github.com/Jain-sonal",
  ],
  [
    "Happy Little Train",
    "./Art/HappyLittleTrain/index.html",
    "./Art/HappyLittleTrain/HappyLittleTrain.gif",
    "John Martin",
    "https://github.com/johnjamesmartin",
  ],
  [
    "City",
    "./Art/City/index.html",
    "./Art/City/city.jpeg",
    "Julitree",
    "https://github.com/julitree",
  ],
  [
    "iqmah",
    "./Art/iqmah/index.html",
    "./Art/iqmah/gallery.png",
    "Hikmah",
    "https://github.com/nrhikmah",
  ],
  [
    "BINGNAN-CHEN",
    "./Art/BINGNAN-CHEN/index.html",
    "./Art/BINGNAN-CHEN/box.jpg",
    "BINGNAN-CHEN",
    "https://github.com/r1991108",
  ],
  [
    "cool-jengwa",
    "./Art/cool-jengwa/index.html",
    "./Art/cool-jengwa/melon-cuts.PNG",
    "jengwa",
    "https://github.com/Jengwa",
  ],
  [
    "cute bear",
    "./Art/carlacentenor/index.html",
    "./Art/carlacentenor/bear.JPG",
    "carlacentenor",
    "https://github.com/carlacentenor",
  ],
  [
    "koala",
    "./Art/fuckupc/index.html",
    "./Art/fuckupc/icon.PNG",
    "fuckupc",
    "https://github.com/fuckupc",
  ],
  [
    "Shy Rabbit",
    "./Art/teits/index.html",
    "./Art/teits/preview.png",
    "Teits",
    "https://github.com/teitss",
  ],
  [
    "Pikachu",
    "./Art/julesdowork/index.html",
    "./Art/julesdowork/pikachu.png",
    "Julesdowork",
    "https://github.com/Julesdowork",
  ],
  [
    "CSS Ace",
    "./Art/TinatheAce/ace.html",
    "./Art/TinatheAce/ace.png",
    "Tina the Ace",
    "https://github.com/nnh242",
  ],
  [
    "Frank",
    "./Art/AndrewDiedrich/index.html",
    "./Art/AndrewDiedrich/Frank.PNG",
    "Andrew Diedrich",
    "https://github.com/AndrewDiedrich",
  ],
  [
    "CSS Dog",
    "./Art/Dog/index.html",
    "./Art/Dog/dog.gif",
    "Chintu Yadav Sara",
    "https://github.com/chintuyadav",
  ],
  [
    "No Face",
    "./Art/saamiyah/no-face.html",
    "./Art/saamiyah/no-face.gif",
    "Saamiyah",
    "https://github.com/Saamiyah",
  ],
  [
    "Mahatma Gandhi",
    "./Art/Mahatma%20Gandhi/index.html",
    "./Art/Mahatma%20Gandhi/Gandhi.png",
    "Chintu Yadav Sara",
    "https://github.com/chintuyadav",
  ],
  [
    "WindMill Animation",
    "./Art/WindMill/index.html",
    "./Art/WindMill/windmill.gif",
    "Chintu Yadav Sara",
    "https://github.com/chintuyadav",
  ],
  [
    "CSS Bird",
    "./Art/Bird/index.html",
    "./Art/Bird/Bird.png",
    "Chintu Yadav Sara",
    "https://github.com/chintuyadav",
  ],
  [
    "Robot friend",
    "./Art/joy/robot.html",
    "./Art/joy/robot.png",
    "Joy",
    "https://github.com/royranger",
  ],
  [
    "Spookiest fr̶iend",
    "./Art/pavel/spooky.html",
    "./Art/pavel/spooky.png",
    "Pavel",
    "https://github.com/pavelisp",
  ],
  [
    "Hamburger",
    "./Art/Aszmel/Hamburger.html",
    "./Art/Aszmel/hamburger.png",
    "Aszmel",
    "https://github.com/Aszmel",
  ],
  [
    "Polish Flag animation",
    "./Art/kris/kris.html",
    "./Art/kris/kris.png",
    "Kris",
    "https://github.com/krzysiekh",
  ],
  [
    "Frog",
    "./Art/TheMicroGirl/frog.html",
    "./Art/TheMicroGirl/frog.PNG",
    "TheMicroGirl",
    "https://github.com/TheMicroGirl",
  ],
  [
    "8-bit style Link",
    "./fischbot/index.html",
    "./Art/fischbot/link.png",
    "Fischbot",
    "https://github.com/fischbot",
  ],
  [
    "Ghost Animation",
    "./Art/ghost/ghost.html",
    "./Art/ghost/ghost.png",
    "Jhonattan",
    "https://github.com/jhonattanbenitez",
  ],
  [
    "Boo",
    "./Art/zach-caldwell/ghost.html",
    "./Art/zach-caldwell/ghost.PNG",
    "Zach",
    "https://github.com/zach-caldwell",
  ],
  [
    "Pumpkin",
    "./Art/Asam/pumpkin.html",
    "./Art/Asam/pumpkin.png",
    "Asam",
    "https://github.com/shan5742",
  ],
  [
    "Funky Pumpkin",
    "./Art/Matt/pumpkin.html",
    "./Art/Matt/icon.PNG",
    "Matt",
    "https://github.com/mattcsmith",
  ],
  [
    "Spooky Androids!",
    "./Art/hmahajan/androids.html",
    "./Art/hmahajan/androids.JPG",
    "hmahajan",
    "https://github.com/hmahajan99",
  ],
  [
    "TrailSnail",
    "./Art/trailsnail/spinner.html",
    "./Art/trailsnail/spinner.png",
    "Complex Spinner",
    "https://github.com/trailsnail",
  ],
  [
    "Spooky Penguine",
    "./Art/Shruti/penguine.html",
    "./Art/Shruti/penguine.PNG",
    "Shruti",
    "https://github.com/shruti49",
  ],
  [
    "Pac-Man Run",
    "./Art/PaulC/pacman_run.html",
    "./Art/PaulC/pac.png",
    "PaulC",
    "https://github.com/m2paulc",
  ],
  [
    "Frankenstein",
    "./Art/josh/frankie.html",
    "./Art/josh/Capture.PNG",
    "Josh",
    "https://github.com/jcothard",
  ],
  [
    "Koala Head",
    "./Art/Are/index.html",
    "./Art/Are/koala.png",
    "Are",
    "https://github.com/Ar3Tea",
  ],
  [
    "CSS Loader",
    "./Art/Frozenfroggie/index.html",
    "./Art/Frozenfroggie/loader.gif",
    "Frozenfroggie",
    "https://github.com/frozenfroggie",
  ],
  [
    "Macho Ghost",
    "./Art/Astro/index.html",
    "./Art/Astro/ghost.jpeg",
    "Amy",
    "https://github.com/astrokwk",
  ],
  [
    "Pumpkin",
    "./Art/katcode/index.html",
    "./Art/katcode/pumpkin.png",
    "katcode",
    "https://github.com/katcode",
  ],
  [
    "Javascript Coffee Cu",
    "./Art/JS Coffee Cup/js_coffee_cup.html",
    "./Art/JS Coffee Cup/js_coffee_cup.gif",
    "Bilal Younso",
    "https://github.com/bilalyounso",
  ],
  [
    "CSS Clock",
    "./Art/Sean-Dees/sean.html",
    "./Art/Sean-Dees/clock.PNG",
    "Sean Dees",
    "https://github.com/sdees82",
  ],
  [
    "Linux",
    "./Art/linux/index.html",
    "./Art/linux/linux.gif",
    "Thea",
    "https://github.com/highflyer910",
  ],
  [
    "Devices",
    "./Art/virtual/index.html",
    "./Art/virtual/virtual.png",
    "Virtual",
    "https://github.com/virtual",
  ],
  [
    "Owl",
    "./Art/owl/owl.html",
    "./Art/owl/owl.png",
    "Thea",
    "https://github.com/highflyer910",
  ],
  [
    "Sunrise and Sunset",
    "./Art/sanjithpk/index.html",
    "./Art/sanjithpk/sun.png",
    "Sanjith",
    "https://github.com/sanjithpk",
  ],
  [
    "Halloween Cat",
    "./Art/Martyav/halloween_cat.html",
    "./Art/Martyav/halloween_cat.png",
    "Martyav",
    "https://github.com/martyav",
  ],
  [
    "Pumpkin",
    "./Art/pohyi-k/index.html",
    "./Art/pohyi-k/pumkin.png",
    "pohyi-k",
    "https://github.com/pohyi-k",
  ],
  [
    "8bit-Pumpkin",
    "./Art/8bit-pumpkin/index.html",
    "./Art/8bit-pumpkin/8bit-Pumpkin.png",
    "MatthewS",
    "https://github.com/MatthewStoddart",
  ],
  [
    "Catrina",
    "./Art/catrina/index.html",
    "./Art/catrina/catrina.png",
    "Tahi",
    "https://github.com/cTahirih",
  ],
  [
    "Run to Win",
    "./Art/run to win/index.html",
    "./Art/run to win/my.png",
    "Sanidhya",
    "https://github.com/sanidhya2000",
  ],
  [
    "Hallucinations",
    "./Art/kahwaii/kahwaii.html",
    "./Art/kahwaii/dizzy.PNG",
    "kahwaii",
    "https://github.com/kahwaii",
  ],
  [
    "CSS Clock",
    "./Art/KwanwooJeong/index.html",
    "./Art/KwanwooJeong/css-clock.png",
    "Kwanwoo Jeong",
    "https://github.com/kwanwooi25",
  ],
  [
    "Bear",
    "./Art/MAG/bear.html",
    "./Art/MAG/bear.png",
    "gettaplay",
    "https://github.com/gettaplay",
  ],
  [
    "SPOOKY FAMILY",
    "./Art/Anca/index.html",
    "./Art/Anca/family.png",
    "Anca",
    "https://github.com/AncaWebDev",
  ],
  [
    "Heart",
    "./Art/mamta/heart.html",
    "./Art/mamta/heart.png",
    "palmamta",
    "https://github.com/palmamta",
  ],
  [
    "The Grim Reaper",
    "./Art/OhSnapdragon/reaper.html",
    "./Art/OhSnapdragon/reaper.PNG",
    "OhSnapdragon",
    "https://github.com/OhSnapdragon",
  ],
  [
    "Flying Bird",
    "./Art/mamta/index2.html",
    "./Art/mamta/flying.png",
    "palmamta",
    "https://github.com/palmamta",
  ],
  [
    "Creepy Selfie",
    "./Art/Creepy Selfie/index.html",
    "./Art/Creepy Selfie/CreepySelfie.png",
    "bronasek",
    "https://github.com/bronasek",
  ],
  [
    "Redvan's Apple",
    "./Art/redvan/index.html",
    "./Art/redvan/redvansApple.jpg",
    "Redvanisation",
    "https://github.com/Redvanisation",
  ],
  [
    "Heart",
    "./Art/Heart/index.html",
    "./Art/Heart/heart.gif",
    "SliceOLife",
    "https://github.com/SliceOLife",
  ],
  [
    "Hamburger",
    "./Art/Nikhil/index.html",
    "./Art/Nikhil/hamburger.png",
    "Nikhil Shrivastava",
    "https://github.com/NikhilShrivastava",
  ],
  [
    "Arc Reactor",
    "./Art/AhmedH14/index.html",
    "./Art/AhmedH14/ScreenShot.png",
    "Ahmed Hajat",
    "https://github.com/AhmedH14",
  ],
  [
    "Pixel Charizard",
    "./Art/mctrl/index.html",
    "./Art/mctrl/charizard.jpg",
    "Martina",
    "https://github.com/mctrl",
  ],
  [
    "Funky Monkey",
    "./Art/andra/index.html",
    "./Art/andra/andra.png",
    "Andra",
    "https://github.com/andrapetronela",
  ],
  [
    "Kirby",
    ".Art/Kirby.index.html",
    "./Art/Kirby/Kirby.png",
    "Aldiekmann",
    "https://github.com/aldiekmann",
  ],
  [
    "Cartoon Skull",
    "./Art/Jose-Rios/index.html",
    "./Art/Jose-Rios/skull_css.JPG",
    "Jose",
    "https://github.com/Riosjl41",
  ],
  [
    "Butterfly",
    "./Art/R-Butterfly/index.html",
    "./Art/R-Butterfly/R-Butterfly.png",
    "Russell",
    "https://github.com/russellsoppe",
  ],
  [
    "Robo - Dancer",
    "./Art/Florin/index.html",
    "./Art/Florin/robo-dancer.png",
    "Florin",
    "https://github.com/LoposFlorin",
  ],
  [
    "Smiley",
    "./Art/adrianomi/index.html",
    "./Art/adrianomi/smiley.jpg",
    "adrianomi",
    "https://github.com/adrianomi",
  ],
  [
    "Watermelon",
    "./Art/watermelon/index.html",
    "./Art/watermelon/watermelon-screenshot.PNG",
    "Dan Horsch",
    "https://github.com/danhorsch",
  ],
  [
    "Beach",
    "./Art/sdfnz/beach.html",
    "./Art/sdfnz/beach.jpg",
    "sdfnz",
    "https://github.com/sdfnz",
  ],
  [
    "Funny Avocado",
    "./Art/yokesharun/index.html",
    "./Art/yokesharun/avocado.png",
    "yokesharun",
    "https://github.com/yokesharun",
  ],
  [
    "Gameboy",
    "./Art/mctrl/gameboy.html",
    "./Art/mctrl/gameboy.jpg",
    "Martina",
    "https://github.com/mctrl",
  ],
  [
    "Frog",
    "./Art/Elin-frog/index.html",
    "./Art/Elin-frog/frog.png",
    "elindjuren",
    "https://github.com/elindjuren",
  ],
  [
    "Fita Cassete",
    "./Art/Pliavi/index.html",
    "./Art/Pliavi/print.png",
    'Vitor "Pliavi" Silvério',
    "https://github.com/Pliavi",
  ],
  [
    "Panda",
    "./Art/Madhuri/index.html",
    "./Art/Madhuri/Screenshot.png",
    "Madhuri Soni",
    "https://github.com/sonimadhuri",
  ],
  [
    "Xmas",
    "./Art/Chrissy/xmas.html",
    "./Art/Chrissy/xmas.png",
    "Chrissy",
    "https://github.com/charlecoda88",
  ],
  [
    "Spooky violin",
    "./Art/JaniH92/index.html",
    "./Art/JaniH92/spookyViolin.GIF",
    "Jani Hänninen",
    "https://github.com/jh1992jh",
  ],
  [
    "Responsive Bars",
    "./Art/Rahul/index.html",
    "./Art/Rahul/index.png",
    "Rahul",
    "https://github.com/rik-96",
  ],
  [
    "Creepy Pumpkin",
    "./Art/Virtual1/Virtual1.html",
    "./Art/Virtual1/Virtual1.bmp",
    "Jessica Erasmus",
    "https://github.com/Virtual1",
  ],
  [
    "Boat",
    "./Art/Boat/index.html",
    "./Art/Boat/Boat.png",
    "Titi Arimba",
    "https://github.com/titiarimba",
  ],
  [
    "Koala",
    "./Art/Chrissy/koala.html",
    "./Art/Chrissy/koalaedit.png",
    "Chrissy",
    "https://github.com/charlecoda88",
  ],
  [
    "Landscape",
    "./Art/David/index.html",
    "./Art/David/landscape.png",
    "The24thDS",
    "https://github.com/the24thds",
  ],
  [
    "Birthday Balloon",
    "./Art/Dazzla2020/index.html",
    "./Art/Dazzla2020/bithday-balloon.png",
    "Dazzla",
    "https://github.com/Dazzla2020",
  ],
  [
    "Spinning Shuriken",
    "./Art/Mr.Zilox/index.html",
    "./Art/Mr.Zilox/ninga.png",
    "Mr.Zilox",
    "https://github.com/mitchellKalcher/",
  ],
  [
    "Sunny apple",
    "./Art/DepSteph/my-art.html",
    "./Art/DepSteph/my-art.png",
    "DepSteph",
    "https://github.com/StephDs",
  ],
  [
    "Airplane",
    "./Art/jen/plane.html",
    "./Art/jen/plane.png",
    "Jen",
    "https://github.com/jenwr",
  ],
  [
    "Mouse",
    "./Art/jen/mouse.html",
    "./Art/jen/mouse.png",
    "Jen",
    "https://github.com/jenwr",
  ],
  [
    "Hungry Caterpillar",
    "./Art/CarmenIancu/index.html",
    "./Art/CarmenIancu/hungry_caterpillar.JPG",
    "CarmenIancu",
    "https://github.com/CarmenIancu",
  ],
  [
    "CSS Flower",
    "./Art/Kim/index.html",
    "./Art/Kim/Flower.png",
    "Kim",
    "https://github.com/QAMinn2468",
  ],
  [
    "Mario Pipe",
    "./Art/iggyzane/index.html",
    "./Art/iggyzane/MarioPipe.PNG",
    "Iggy Baker",
    "https://github.com/iggyzane",
  ],
  [
    "Pizza",
    "./Art/carter/pizza.html",
    "./Art/carter/pizza.png",
    "Carter",
    "https://github.com/carterschieffer",
  ],
  [
    "Rocket",
    "./Art/cbh6/rocket.html",
    "./Art/cbh6/rocket.jpg",
    "Cristian",
    "https://github.com/cbh6",
  ],
  [
    "Space Invader",
    "./Art/JFox/spaceInvader.html",
    "./Art/JFox/spaceInvader.png",
    "Jeremy Fox",
    "https://github.com/jeremyfox36",
  ],
  [
    "Cactus in a Pot",
    "./Art/danIancuV/index.html",
    "./Art/danIancuV/CactusInAPot.jpg",
    "danIancuV",
    "https://github.com/danIancuV",
  ],
  [
    "Beating Heart",
    "./Art/nikiya/index.html",
    "./Art/nikiya/heart-beat.png",
    "Nikiya Simpson",
    "https://github.com/nikiyasimpson",
  ],
  [
    "Waving Penguin",
    "./Art/orinayo/index.html",
    "./Art/orinayo/penguin_art.png",
    "Orinayo Oyelade",
    "https://github.com/orinayo",
  ],
  [
    "Taco Animation",
    "./Art/roninmittal/index.html",
    "./Art/roninmittal/taco.png",
    "Ronin Mittal",
    "https://github.com/roninmittal",
  ],
  [
    "Ghost",
    "./Art/toserjude/ghost.html",
    "./Art/toserjude/ghost.jpg",
    "toserjude",
    "https://github.com/toserjude",
  ],
  [
    "JS Logo",
    "./Art/Thulasi/index.html",
    "./Art/Thulasi/js-logo.PNG",
    "ThulasiA",
    "https://github.com/ThulasiA",
  ],
  [
    "Black Cat",
    "./Art/toserjude/blackCat.html",
    "./Art/toserjude/cat.jpg",
    "toserjude",
    "https://github.com/toserjude",
  ],
  [
    "Minimalist Hover and Move Away",
    "./Art/JoyceMinimalistArt/index.html",
    "./Art/JoyceMinimalistArt/joycemini.png",
    "Joyce Wambui",
    "https://github.com/joycewambui",
  ],
  [
    "Baymax",
    "./Art/dziukers/index.html",
    "./Art/dziukers/Baymax.JPG",
    "dziukers",
    "https://github.com/dziukers",
  ],
  [
    "Smart Phone",
    "./Art/chathurasam/smartphone.html",
    "./Art/chathurasam/screenshot.png",
    "Chathura Samarajeewa",
    "https://github.com/ChathuraSam",
  ],
  [
    "Pikachu",
    "./Art/Sherin/pikachu.html",
    "./Art/Sherin/pikachu.png",
    "Sherin Binu",
    "https://github.com/SherOnDale",
  ],
  [
    "Fox",
    "./Art/Platy/index.html",
    "./Art/Platy/fox.png",
    "Atti",
    "https://github.com/Platyka",
  ],
  [
    "Just alone panda",
    "./Art/justpanda/index.html",
    "./Art/justpanda/panda.PNG",
    "Maximsan",
    "https://github.com/maximsan",
  ],
  [
    "Squirtle",
    "./Art/Sherin/squirtle.html",
    "./Art/Sherin/squirtle.png",
    "Sherin Binu",
    "https://github.com/SherOnDale",
  ],
  [
    "Butterfree",
    "./Art/Sherin/butterfree.html",
    "./Art/Sherin/butterfree.png",
    "Sherin Binu",
    "https://github.com/SherOnDale",
  ],
  [
    "Captain's Shield",
    "./Art/napvlm/shield.html",
    "./Art/napvlm/shield.png",
    "Ruslan Anisimov",
    "https://github.com/napvlm",
  ],
  [
    "Happy Emoji",
    "./Art/uhayon/emoji.html",
    "./Art/uhayon/emoji.png",
    "Uri",
    "https://github.com/uhayon",
  ],
  [
    "Electrode",
    "./Art/Sherin/electrode.html",
    "./Art/Sherin/electrode.png",
    "Sherin Binu",
    "https://github.com/SherOnDale",
  ],
  [
    "Mounion vaakuna",
    "./Art/MAhoMaha12112017/MAhoMaha12112017.html",
    "./Art/MAhoMaha12112017/mouniovaakuna_pieni_skaalattu.png",
    "MAho",
    "https://github.com/MAhoMaha12112017",
  ],
  [
    "bouncing ball",
    "./Art/jaeja/index.html",
    "./Art/jaeja/ball.png",
    "jae",
    "https://github.com/jaeja",
  ],
  [
    "Egg",
    "./Art/tomikonio/egg.html",
    "./Art/tomikonio/egg.png",
    "tomikonio",
    "https://github.com/tomikonio",
  ],
  [
    "Shaky Wall",
    "./Art/tsrumia/index.html",
    "./Art/tsrumia/image.jpg",
    "Tsrumia",
    "https://github.com/mukherj",
  ],
  [
    "Birthday cake",
    "./Art/KarinPR/index.html",
    "./Art/KarinPR/Birthday_cake.png",
    "Karin Povolozki-Rabichev",
    "https://github.com/KarinPR",
  ],
  [
    "Skype logo",
    "./Art/ddoyediran/index12.html",
    "./Art/ddoyediran/Skype-logo.jpg",
    "Damilare Oyediran",
    "https://github.com/ddoyediran",
  ],
  [
    "The Minimal Artist",
    "./Art/Arpit Jain/Arpit Jain.html",
    "./Art/Arpit Jain/Arpit Jain.png",
    "Arpit Jain",
    "https://github.com/arpitjainds",
  ],
  [
    "Minimal Clown",
    "./Art/Jithendra Yenugula/jithendrabsy.html",
    "./Art/Jithendra Yenugula/jithendrabsy.png",
    "Jithendra Yenugula",
    "https://github.com/jithendrabsy",
  ],
  [
    "Square Fox",
    "./Art/Fox/index.html",
    "./Art/Fox/fox.png",
    "Bruno Bolting",
    "https://github.com/brunobolting",
  ],
  [
    "Cub",
    "./Art/matheusagcosta/index.html",
    "./Art/matheusagcosta/cub.png",
    "matheusagcosta",
    "https://github.com/matheusagcosta",
  ],
  [
    "Airpods",
    "./Art/KatrinaRose14/index.html",
    "./Art/KatrinaRose14/airpods.png",
    "Katrina Rose Yates",
    "https://github.com/KatrinaRose14",
  ],
  [
    "Lambda",
    "./Art/felipp/index.html",
    "./Art/felipp/lambda.png",
    "felipp",
    "https://github.com/skelrilod",
  ],
  [
    "Ringing bell",
    "./Art/RedSquirrrel/index.html",
    "./Art/RedSquirrrel/ringing bell.png",
    "Anette",
    "https://github.com/RedSquirrrel",
  ],
  [
    "animated-face",
    "./Art/Saksham/index.html",
    "./Art/Saksham/animated-face.png",
    "Saksham Singh",
    "https://github.com/Saksham27",
  ],
  [
    "Animated Circle",
    "./Art/Sravya/index.html",
    "./Art/Sravya/index.png",
    "Sravya Challa",
    "https://github.com/sravya-challa-au3",
  ],
  [
    "Turn Around",
    "./Art/Hila/index.html",
    "./Art/Hila/animation_Gif.gif",
    "Hila Ailon",
    "https://github.com/Hila-Ailon",
  ],
  [
    "Christmas Tree",
    "./Art/Ablutie/index.html",
    "./Art/Ablutie/christmasTree.jpg",
    "Mihai Dragomir",
    "https://github.com/Ablutie",
  ],
  [
    "AtariNTSCColors",
    "./Art/GiantsCode/index.html",
    "./Art/GiantsCode/AtariNTSCColors.gif",
    "Daniel Macleod GiantsCode",
    "https://github.com/giantscode",
  ],
  [
    "Heart Animation",
    "./Art/RenaOnFire/index.html",
    "./Art/RenaOnFire/HeartImage.png",
    "Rena OnFire",
    "https://github.com/renaonfire",
  ],
  [
    "Anonymus Animation",
    "/Art/Anonymus/anonymus.html",
    "/Art/Anonymus/9mi2FINz_400x400.jpg",
    "Hope somebody will find this funny",
    "https://github.com/Jurek33",
  ],
  [
    "Rolling circle animation",
    "/Art/Kenneth/index.html",
    "Art/Kenneth/rolling_circle.jpg",
    "Kenneth Skodje",
    "https://github.com/KSkodje",
  ],
  [
    "Pokeball",
    "./Art/AdityaSaroj/index.html",
    "./Art/AdityaSaroj/pokeball.png",
    "Aditya Kumar Saroj",
    "https://github.com/AdityaSaroj",
  ],
  [
    "Forest Racer",
    "./Art/rainoverme002/index.html",
    "./Art/rainoverme002/forest-racer.png",
    "rainoverme002",
    "https://github.com/rainoverme002",
  ],
  [
    "Drop",
    "./Art/ikaem/index.html",
    "./Art/ikaem/drop.gif",
    "ikaem",
    "https://github.com/ikaem",
  ],
  [
    "Drop",
    "./Art/Wow/index.html",
    "./Art/Wow/wow.gif",
    "sagihill",
    "https://github.com/sagihill",
  ],
  [
    "Rotate",
    "./Art/Abio/index.html",
    "./Art/Abio/Screenshot.png",
    "abiola-ajibola",
    "https://github.com/abiola-ajibola",
  ],
  [
    "Gangnam",
    "./Art/Gangnam/index.html",
    "./Art/Gangnam/gangnam.png",
    "Ibrahim Tarabay",
    "https://github.com/IbrahimTarabay",
  ],
  [
    "CSS Cube Perspective",
    "./Art/carljustineoyales/index.html",
    "./Art/carljustineoyales/CSSCubePerspective.gif",
    "Carl Justine Oyales",
    "https://github.com/carljustineoyales",
  ],
  [
    "Strange Ball",
    "./Art/ronchito13/index.html",
    // "./Art/ronchito13/ball.gif",
    "", // no artwork in folder
    "Ronchito13",
    "https://github.com/Ronchito13",
  ],
  [
    "Art-E-opera",
    "./Art/mayIGit_meg/index.html",
    "./Art/mayIGit_meg/cover2.gif",
    "mayIGit",
    "https://github.com/mayIGit",
  ],
  [
    "CSS Mosaic Layout",
    "./Art/mosaic-layout/index.html",
    "./Art/mosaic-layout/mosaic.png",
    "collinsmuriuki",
    "https://github.com/collinsmuriuki",
  ],
  [
    "Smiling Clown",
    "./Art/VelizarStavrev/index.html",
    "./Art/VelizarStavrev/smilingClown.png",
    "VelizarStavrev",
    "https://github.com/VelizarStavrev",
  ],
  [
    "Fishes",
    "./Art/Fishes/index.html",
    "./Art/Fishes/fishes.png",
    "Konstantin Dergachev",
    "https://github.com/konstantindergachev",
  ],
  [
    "Animate The Button",
    "./Art/krishan93985/index.html",
    "./Art/krishan93985/animation.png",
    "krishan93985",
    "https://github.com/krishan93985",
  ],
  [
    "Cosmos",
    "./Art/prajwal-mendon/index.html",
    "./Art/prajwal-mendon/cosmos.png",
    "Prajwal Mendon",
    "https://github.com/Prajwal-mendon",
  ],
  [
    "My not-so Flashy Animation",
    "./Art/SonalJain/index.html",
    "./Art/SonalJain/My not-so Flashy Animation.gif",
    "Sonal Jain",
    "https://github.com/Jain-sonal",
  ],
  [
    "Happy Little Train",
    "./Art/HappyLittleTrain/index.html",
    "./Art/HappyLittleTrain/HappyLittleTrain.gif",
    "John Martin",
    "https://github.com/johnjamesmartin",
  ],
  [
    "City",
    "./Art/City/index.html",
    "./Art/City/city.jpeg",
    "Julitree",
    "https://github.com/julitree",
  ],
  [
    "ReactLogo",
    "./Art/Jorjill/index.html",
    "./Art/Jorjill/ReactLogo.png",
    "JohnJorjill",
    "https://github.com/JohnJorjill",
  ],
  [
    "Bubble",
    "./Art/bubble/index.html",
    "./Art/bubble/bubble.png",
    "theo",
    "https://github.com/Theofylaktos",
  ],
  [
    "Css Image Gallery",
    "./Art/iqmah/index.html",
    "./Art/iqmah/gallery.png",
    "iqmah",
    "https://github.com/nrhikmah",
  ],
  [
    "Goga AnimatedGallery",
    "./Art/Goga AnimatedGallery/index.html",
    "./Art/Goga AnimatedGallery/Goga.gif",
    "Goga",
    "https://github.com/gogadev",
  ],
  [
    "CSS Funny Face",
    "./Art/MColeman/index.html",
    "./Art/MColeman/FunnyFace.JPG",
    "Mike Coleman",
    "https://github.com/mcflav",
  ],
  [
    "trying",
    "./Art/vilasiniCSS/bg.html",
    "", // no artwork in folder
    "vilasini",
    "https://github.com/vilasinisaida",
  ],
  [
  "Blast Off",
    "./Art/mjbh831/index.html",
    "./Art/mjbh831/blastOff.png",
    "Marcos Hinojos",
    "https://github.com/mjbh831",
  ],
  [
    "Pug's Life",
    "./Art/MindyLJohnson/index.html",
    "./Art/MindyLJohnson/pugGIF.gif",
    "Mindy Johnson",
    "https://github.com/MindyLJohnson",
  ],
  [
    "Eyeball",
    "./Art/AnathKantonda/index.html",
    "./Art/AnathKantonda/bouncing-moving-eye.PNG",
    "Anath Kantonda",
    "https://github.com/anathkantonda",
  ],
  [
    "AniFun",
    "./Art/anifun/index.html",
    "./Art/anifun/anifun.gif",
    "Yorvin Luna Wisky",
    "https://github.com/yorvinlunawisky",
  ],
  [
    "ChristmasTree",
    "./Art/KiritoJX/index.html",
    "./Art/KiritoJX/cover.png",
    "Phu Le Ngo",
    "https://github.com/kiritojx",
  ],
  [
    "russellbot",
    "./Art/russellbot/index.html",
    "./Art/russellbot/russellbot.png",
    "russellbot",
    "https://github.com/russellbot"
  ],
  // folder is empty so commented out
  // [
  //   "fvlly",
  //   "./Art/fvlly/index.html",
  //   "./Art/fvlly/animations.png",
  //   "Luqman A Ibrahim",
  //   "https://github.com/fvlly",
  // ],
  ["FunZoo",
    "./Art/elamarang/index.html",
    "./Art/elamarang/zoo.png",
    "elamarang",
    "https://github.com/elamarang"
  ],
  [
    "Flying Bird from Steven Roberts",
    "./Art/itkhanz/index.html",
    "./Art/itkhanz/screenshot.jpg",
    "itkhanz",
    "https://github.com/itkhanz"
  ],
  [
    "Bar-animation",
    "./Art/farhanali3193/index.html",
    "./Art/farhanali3193/Bars.png",
    "farhanali3193",
    "https://github.com/farhanali3193"
  ],
  [
  "Mahi",
  "./Art/Mahi/index.html",
  "./Art/Mahi/trance.gif",
  "Mahiprabhu",
  "https://github.com/Mahiprabhu"
  ],
  [
  "Projects",
  "./Art/dpletzke/index.html",
  "./Art/dpletzke/Projects.png",
  "dpletzke",
  "https://github.com/dpletzke"
  ]
];


// +--------------------------------------------------------------------------------+
// +                                                                                +
// +                  YOU DO NOT NEED TO CHANGE ANYTHING BELOW THIS                 +
// +                                                                                +
// +--------------------------------------------------------------------------------+

// Creates cards from the array above
// You don't need to modify this
let contents = [];
Shuffle(cards).forEach((c) => {
  contents.push([
    `<li class="card">` +
    `<img class="art-image" src='${c[2]}' alt='${c[0]}' />` +
    `<div class="flex-content">` +
    `<a href='${c[1]}'><h3 class="art-title">${c[0]}</h3></a>` +
    `<p class='author'><a href="${c[4]}" target="_blank"><i class="fab fa-github"></i> ${c[3]}</a> </p>` +
    `</div>` +
    `</li>`,
  ]);
});

document.getElementById("cards").innerHTML = contents;

function Shuffle(o) {
  for (
    var j, x, i = o.length;
    i;
    j = parseInt(Math.random() * i), x = o[--i], o[i] = o[j], o[j] = x
  );
  return o;
}
