let cards = [
  //  Add your card in this section

  {
    artName: "Pikachu",
    pageLink: "./Art/shahina/index.html",
    author: "Shahina",
    githubLink: "https://github.com/ShahinaShanu",
  },
  {
    artName: "Pretty Duck",
    pageLink: "./Art/1.ani/index.html",
    author: "O-zbair",
    githubLink: "https://github.com/O-zbair",
  },
{
    artName: "Funky Clock",
    pageLink: "",
    author: "Prakhar",
    githubLink: "https://github.com/prakharbaphna",
  },
  {
    artName:'Pizza slice',
    pageLink: './Art/fernando122/pizza.html',
    imageLink:'./Art/fernando122/pizza.png',
    author: 'JFernando122',
    githubLink:'https://github.com/JFernando122'
  },
  {
    artName: "Planet Loader",
    pageLink: "./Art/sherine/index.html",
    author: "Sherine",
    githubLink: "https://github.com/sherinechally",
  },
  {
    artName: "Doraemon",
    pageLink: "./Art/DevarshiDoshi/index.html",
    imageLink: "./Art/DevarshiDoshi/Doraemon.png",
    author: "Devarshi Doshi",
    githubLink: "https://github.com/devarshidoshi",
  },

  {
    artName: "Vitrola",
    pageLink: "./Art/Pliavi/vitrola.html",
    author: "Pliavi",
    githubLink: "https://github.com/Pliavi",
    imageLink: "./Art/Pliavi/vitrola.jpg",
  },
  {
    artName: "sun-moon",
    pageLink: "./Art/shinelikeasmile/h.html",
    imageLink: "./Art/shinelikeasmile/g.gif",
    author: "shinelikeasmile",
    githubLink: "https://github.com/shinelikeasmile",
  },
  {
    artName: "beating heart",
    pageLink: "./Art/kelvinchan2406/index.html",
    imageLink: "./Art/kelvinchan2406/heart.png",
    author: "kelvinchan2406",
    githubLink: "https://github.com/kelvinchan2406",
  },
  {
    artName: "That Animation",
    pageLink: "./Art/MaKloudz/index.html",
    imageLink: "./Art/MaKloudz/dat-animation.gif",
    author: "Blessing Mutava",
    githubLink: "https://github.com/MaKloudz",
  },
  {
    artName: "That Animation",
    pageLink: "./Art/MaKloudz/index.html",
    imageLink: "./Art/MaKloudz/dat-animation.gif",
    author: "Blessing Mutava",
    githubLink: "https://github.com/MaKloudz",
  },
  {
    artName: "spirals",
    pageLink: "./Art/Krishna/index.html",
    imageLink: "./Art/Krishna/spiral.png",
    author: "Krishna Kant Hati",
    githubLink: "https://github.com/krishnakanthati",
  },
  {
    artName: "ZTM Animation",
    pageLink: "./Art/EricPuskas/index.html",
    imageLink: "./Art/EricPuskas/index.gif",
    author: "Eric Puskas",
    githubLink: "https://github.com/EricPuskas",
  },
  {
    artName: "LSD Rainbow Trip: Phase 1",
    pageLink: "./Art/AbsMechanik/index.html",
    imageLink: "./Art/AbsMechanik/AbsMechanik_Animation.gif",
    author: "AbsMechanik",
    githubLink: "https://github.com/AbsMechanik",
  },
  {
    artName: "Crystal ball",
    pageLink: "./Art/reekrajroy/index.html",
    imageLink: "./Art/reekrajroy/crystal.PNG",
    author: "Reekraj Roy",
    githubLink: "https://github.com/REEKRAJROY",
  },
  {
    artName: "space zoo",
    pageLink: "./Art/space_zoo/index.html",
    imageLink: "./Art/space_zoo/space_zoo.gif",
    author: "yuwenGithub",
    githubLink: "https://github.com/yuwenGithub",
  },
  {
    artName: "ZTM Animation",
    pageLink: "./Art/EricPuskas/index.html",
    imageLink: "./Art/EricPuskas/index.gif",
    author: "Eric Puskas",
    githubLink: "https://github.com/EricPuskas",
  },
  {
    artName: "LSD Rainbow Trip: Phase 1",
    pageLink: "./Art/AbsMechanik/index.html",
    imageLink: "./Art/AbsMechanik/AbsMechanik_Animation.gif",
    author: "AbsMechanik",
    githubLink: "https://github.com/AbsMechanik",
  },
  {
    artName: "space zoo",
    pageLink: "./Art/space_zoo/index.html",
    imageLink: "./Art/space_zoo/space_zoo.gif",
    author: "yuwenGithub",
    githubLink: "https://github.com/yuwenGithub",
  },
  {
    artName: "flying F",
    pageLink: "./Art/JoshuaCode1/index.html",
    imageLink: "./Art/JoshuaCode1/cssArt.png",
    author: "JoshuaCode1",
    githubLink: "https://github.com/JoshuaCode1",
  },
  {
    artName: "eyes",
    pageLink: "./Art/eyes/index.html",
    imageLink: "./Art/eyes/eyes.gif",
    author: "yuwenGithub",
    githubLink: "https://github.com/yuwenGithub",
  },
  {
    artName: "Spooktober Hacktoberfest",
    pageLink: "./Art/FredAmartey/index.html",
    imageLink: "./Art/FredAmartey/thumbnaill.gif",
    author: "Fred Amartey",
    githubLink: "https://github.com/FredAmartey",
  },
  {
    artName: "Star Wars?",
    pageLink: "./Art/henryvalbuena/index.html",
    imageLink: "./Art/henryvalbuena/index.gif",
    author: "Henry Valbuena",
    githubLink: "https://github.com/henryvalbuena",
  },
  {
    artName: "The Ripple",
    pageLink: "./Art/Anmol2/index.html",
    imageLink: "./Art/Anmol2/ripple.png",
    author: "Anmol",
    githubLink: "https://github.com/Anmol270900",
  },
  {
    artName: "Rainbow loader",
    pageLink: "./Art/ka-hn/rainbow.html",
    imageLink: "./Art/ka-hn/rainbow.gif",
    author: "Karim Hussain",
    githubLink: "https://github.com/ka-hn",
  },
  {
    artName: "The Sun",
    pageLink: "./Art/Anmol/index.html",
    imageLink: "./Art/Anmol/sun.png",
    author: "Anmol",
    githubLink: "https://github.com/Anmol270900",
  },
  {
    artName: "Flipbox",
    pageLink: "./Art/Prasheel/index.html",
    imageLink: "./Art/Prasheel/flip.gif",
    author: "Prasheel Soni",
    githubLink: "https://github.com/ps011",
  },
  {
    artName: "2019 Wave",
    pageLink: "./Art/chris-aqui/index.html",
    imageLink: "./Art/chris-aqui/2019-jump.gif",
    author: "Christine Aqui",
    githubLink: "https://github.com/christine-aqui",
  },
  {
    artName: "Hover Button Animation",
    pageLink: "./Art/Vipul/hover.html",
    imageLink: "./Art/Vipul/Screenshot2.png",
    author: "Vipul",
    githubLink: "https://github.com/vipuljain08",
  },
  {
    artName: "Start From Zero",
    pageLink: "./Art/Robihdy/index.html",
    imageLink: "./Art/Robihdy/start-from-zero.png",
    author: "Robihdy",
    githubLink: "https://github.com/Robihdy",
  },
  {
    artName: "Sliding Lines",
    pageLink: "./Art/erics0n/sliding-lines/index.html",
    imageLink: "./Art/erics0n/sliding-lines/image.gif",
    author: "erics0n",
    githubLink: "https://github.com/erics0n",
  },
  {
    artName: "Burger Menu",
    pageLink: "./Art/mctrl/burger.html",
    imageLink: "./Art/mctrl/burger.gif",
    author: "Martina",
    githubLink: "https://github.com/mctrl",
  },
  {
    artName: "Square Loader",
    pageLink: "./Art/Hemant/index.html",
    imageLink: "./Art/Hemant/loader.gif",
    author: "Hemant Garg",
    githubLink: "https://github.com/hemant-garg",
  },
  {
    artName: "wake up, neo...",
    pageLink: "./Art/samirjouni/TributeToTheMatrix.html",
    imageLink: "./Art/samirjouni/sample.gif",
    author: "Samir Jouni",
    githubLink: "https://github.com/samirjouni",
  },
  {
    artName: "Tribute To COD4MW",
    pageLink: "./Art/samirjouni2/index.html",
    imageLink: "./Art/samirjouni2/sample.gif",
    author: "Samir Jouni",
    githubLink: "https://github.com/samirjouni",
  },
  {
    artName: "Planet",
    pageLink: "./Art/ArthurDoom/planet.html",
    imageLink: "./Art/ArthurDoom/planet.gif",
    author: "ArthurDoom",
    githubLink: "https://github.com/ArthurDoom",
  },
  {
    artName: "SquarPy",
    pageLink: "./Art/Utkarsh/index.html",
    imageLink: "./Art/Utkarsh/hack.gif",
    author: "utkarsh",
    githubLink: "https://github.com/Utkarsh2604",
  },
  {
    artName: "Circle",
    pageLink: "./Art/Oliver/Circle.html",
    imageLink: "./Art/Oliver/circle.gif",
    author: "Oliver",
    githubLink: "https://github.com/oliver-gomes",
  },
  {
    artName: "Ellipse Loader",
    pageLink: "./Art/VaibhavKhulbe/EllipseLoader.html",
    imageLink: "./Art/VaibhavKhulbe/ellipseLoader.gif",
    author: "Vaibhav Khulbe",
    githubLink: "https://github.com/Kvaibhav01",
  },
  {
    artName: "Simple Loader",
    pageLink: "./Art/soumsps/simpleload.html",
    imageLink: "./Art/soumsps/sample.gif",
    author: "Soumendu Sinha",
    githubLink: "https://github.com/soumsps",
  },
  {
    artName: "Rollodex",
    pageLink: "./Art/Shruti/rolling.html",
    imageLink: "./Art/Shruti/rolling.gif",
    author: "Shruti",
    githubLink: "https://github.com/shruti49",
  },
  {
    artName: "Cute Cat",
    pageLink: "./Art/Alghi/cat.html",
    imageLink: "./Art/Alghi/cat.gif",
    author: "Alghi",
    githubLink: "https://github.com/darklordace",
  },
  {
    artName: "ZtM Text",
    pageLink: "./Art/Di4iMoRtAl/ZtM_text_animation.html",
    imageLink: "./Art/Di4iMoRtAl/ZtM_animation.gif",
    author: "Di4iMoRtAl",
    githubLink: "https://github.com/dppeykov",
  },
  {
    artName: "Circles",
    pageLink: "./Art/Bhuvana/circles.html",
    imageLink: "./Art/Bhuvana/circles.gif",
    author: "Bhuvana",
    githubLink: "https://github.com/bhuvana-guna",
  },
  {
    artName: "Bird",
    pageLink: "./Art/Bhuvana/bird.html",
    imageLink: "./Art/Bhuvana/bird.gif",
    author: "Bhuvana",
    githubLink: "https://github.com/bhuvana-guna",
  },
  {
    artName: "Loader",
    pageLink: "./Art/Bhuvana/loader.html",
    imageLink: "./Art/Bhuvana/loader.gif",
    author: "Bhuvana",
    githubLink: "https://github.com/bhuvana-guna",
  },
  {
    artName: "Css Pulse",
    pageLink: "./Art/Aszmel/pulse.html",
    imageLink: "./Art/Aszmel/css_pulse.gif",
    author: "Aszmel",
    githubLink: "https://github.com/Aszmel",
  },
  {
    artName: "Circle Bounce",
    pageLink: "./Art/Edmund/index.html",
    imageLink: "./Art/Edmund/circle-bounce.gif",
    author: "Edmund",
    githubLink: "https://github.com/edmund1645",
  },
  {
    artName: "Heart Beating",
    pageLink: "./Art/Regem/index.html",
    imageLink: "./Art/Regem/heart.jpg",
    author: "Regem",
    githubLink: "https://github.com/GemzBond",
  },
  {
    artName: "Fading Circles",
    pageLink: "./Art/Ankit/fadeCircle.html",
    imageLink: "./Art/Ankit/fadeCircles.png",
    author: "Ankit Srivastava",
    githubLink: "https://github.com/a18nov",
  },
  {
    artName: "Hacktoberfest 2019",
    pageLink: "./Art/jpk3lly/animation.html",
    imageLink: "./Art/jpk3lly/JPs_Animation_GIF.gif",
    author: "jpk3lly",
    githubLink: "https://github.com/jpk3lly",
  },
  {
    artName: "Name Rotator",
    pageLink: "./Art/Meet/name.html",
    imageLink: "./Art/Meet/name.gif",
    author: "Meet",
    githubLink: "https://github.com/Meet1103",
  },
  {
    artName: "Ball Rotator",
    pageLink: "./Art/Bibekpreet/index.html",
    imageLink: "./Art/Bibekpreet/ball.gif",
    author: "Bibekpreet",
    githubLink: "https://github.com/bibekpreet99",
  },
  {
    artName: "Loading",
    pageLink: "./Art/jh1992jh/loading.html",
    imageLink: "./Art/jh1992jh/loading.gif",
    author: "jh1992jh",
    githubLink: "https://github.com/jh1992jh",
  },
  {
    artName: "ZTM Colors",
    pageLink: "./Art/Godnon/index.html",
    imageLink: "./Art/Godnon/ZTMcAnim.gif",
    author: "Godnon",
    githubLink: "https://github.com/godnondsilva",
  },
  {
    artName: "Hover Effect",
    pageLink: "./Art/Shubhankar/index.html",
    imageLink: "./Art/Shubhankar/hackoctober.gif",
    author: "Shubhankar",
    githubLink: "https://github.com/shubhdwiv12",
  },
  {
    artName: "5 balls preloader",
    pageLink: "./Art/Nnaji-Victor/index.html",
    imageLink: "./Art/Nnaji-Victor/5_balls.gif",
    author: "Nnaji Victor",
    githubLink: "https://github.com/Nnaji-Victor",
  },
  {
    artName: "ZTM Bouncer",
    pageLink: "./Art/Josia/bouncer.html",
    imageLink: "./Art/Josia/ztmbouncer.gif",
    author: "Josia Rodriguez",
    githubLink: "https://github.com/josiarod",
  },
  {
    artName: "Hacktober loading animation",
    pageLink: "./Art/mehul1011/index.html",
    imageLink: "./Art/mehul1011/loading.gif",
    author: "Mehul1011",
    githubLink: "https://github.com/mehul1011",
  },
  {
    artName: "Loading Dots",
    pageLink: "./Art/devSergiu/index.html",
    imageLink: "./Art/devSergiu/loading.gif",
    author: "devSergiu",
    githubLink: "https://github.com/devsergiu",
  },
  {
    artName: "TypeWriter effect",
    pageLink: "./Art/Sidharth/Typing_Text.html",
    imageLink: "./Art/Sidharth/type_writer.gif",
    author: "Sidharth",
    githubLink: "https://github.com/Sidharth98",
  },
  {
    artName: "Blue Spin",
    pageLink: "./Art/JamesW/index.html",
    imageLink: "./Art/JamesW/hacktober_spin.gif",
    author: "James Whitney",
    githubLink: "https://github.com/jameswhitney",
  },
  {
    artName: "Loading Animation",
    pageLink: "./Art/Sidharth/Loading.html",
    imageLink: "./Art/Sidharth/Loading.gif",
    author: "Sidharth",
    githubLink: "https://github.com/Sidharth98",
  },
  {
    artName: "Rotation",
    pageLink: "./Art/alenanog/index.html",
    imageLink: "./Art/alenanog/rotation.gif",
    author: "Alena A.",
    githubLink: "https://github.com/alenanog",
  },
  {
    artName: "Colors in your life",
    pageLink: "./Art/Atipahy/colors.html",
    imageLink: "./Art/Atipahy/colors.png",
    author: "Christos Chr",
    githubLink: "https://github.com/atipaHy",
  },
  {
    artName: "Orb",
    pageLink: "./Art/Jkbicbic/orb.html",
    imageLink: "./Art/Jkbicbic/orb.gif",
    author: "John Kennedy Bicbic",
    githubLink: "https://github.com/jkbicbic",
  },
  {
    artName: "Charging...",
    pageLink: "./Art/Afraz/charging.html",
    imageLink: "./Art/Afraz/charging.gif",
    author: "Afraz",
    githubLink: "https://github.com/afrazz",
  },
  {
    artName: "Charging...",
    pageLink: "./Art/DepStep/depstep.html",
    imageLink: "./Art/DepStep/depstep.gif",
    author: "DepStep",
    githubLink: "https://github.com/stephD",
  },
  {
    artName: "Dancing Ball...",
    pageLink: "./Art/DaveFres/index.html",
    imageLink: "./Art/DaveFres/ball.gif",
    author: "DaveFres",
    githubLink: "https://github.com/DaveFres",
  },
  {
    artName: "Sunshine",
    pageLink: "./Art/Pavelisp/sunshine.html",
    imageLink: "./Art/Pavelisp/sunshine.gif",
    author: "Pavel Isp",
    githubLink: "https://github.com/pavelisp",
  },
  {
    artName: "Cheshire",
    pageLink: "./Art/Ckanelin/index.html",
    imageLink: "./Art/Ckanelin/Cheshire.gif",
    author: "Ckanelin",
    githubLink: "https://github.com/ckanelin",
  },
  {
    artName: "Disappear",
    pageLink: "./Art/Stacy/index.html",
    imageLink: "./Art/Stacy/disappear.gif",
    author: "Stacy",
    githubLink: "https://github.com/stacyholtz6",
  },
  {
    artName: "Ellipse Spinner",
    pageLink: "./Art/Sabina/ellipse_spinner.html",
    imageLink: "./Art/Sabina/ellipse_spinner.png",
    author: "Sabina Abbasova",
    githubLink: "https://github.com/sabina929",
  },
  {
    artName: "NightSky",
    pageLink: "./Art/AndyS/index.html",
    imageLink: "./Art/AndyS/Capture.GIF",
    author: "AndyS",
    githubLink: "https://github.com/AndyS1988",
  },
  {
    artName: "Hungry",
    pageLink: "./Art/diegchav/index.html",
    imageLink: "./Art/diegchav/hungry.gif",
    author: "Diego Chz",
    githubLink: "https://github.com/diegchav",
  },
  {
    artName: "Colorize",
    pageLink: "./Art/JimBratsos/colorize.html",
    imageLink: "./Art/JimBratsos/Colorize.gif",
    author: "Jim Bratsos",
    githubLink: "https://github.com/JimBratsos",
  },
  {
    artName: "Hacktober Spooktacular",
    pageLink: "Art/Elex/index.html",
    imageLink: ["./Art/Elex/hhs.gif"],
    author: "William Poisel (LordCobra)",
    githubLink: "https://github.com/epoisel",
  },
  {
    artName: "Circley",
    pageLink: "./Art/Tranjenny/indexjenny.html",
    imageLink: "./Art/Tranjenny/zerojenny.gif",
    author: "Tranjenny",
    githubLink: "https://github.com/Tranjenny",
  },
  {
    artName: "My Vietnam",
    pageLink: "./Art/nhbduy/index.html",
    imageLink: "./Art/nhbduy/my-vietnam.gif",
    author: "Hoang-Bao-Duy NGUYEN",
    githubLink: "https://github.com/nhbduy",
  },
  {
    artName: "Hactoberfest Bus",
    pageLink: "./Art/shahpranaf/index.html",
    imageLink: "./Art/shahpranaf/hacktoberfest_bus.gif",
    author: "Pranav Shah",
    githubLink: "https://github.com/shahpranaf",
  },
  {
    artName: "Hacktoberfest",
    pageLink: "./Art/robihid/index.html",
    imageLink: "./Art/robihid/hacktoberfest.png",
    author: "robihid",
    githubLink: "https://github.com/robihid",
  },
  {
    artName: "Hi there",
    pageLink: "./Art/Aki/index.html",
    imageLink: "./Art/Aki/giphy.gif",
    author: "Aki",
    githubLink: "https://github.com/akmalist",
  },
  {
    artName: "Hacktoberfest 2019!",
    pageLink: "./Art/RedSquirrrel/index.html",
    imageLink: "./Art/RedSquirrrel/index.html/animation.PNG",
    author: "RedSquirrrel",
    githubLink: "https://github.com/RedSquirrrel",
  },
  {
    artName: "Sliding text",
    pageLink: "./Art/Flattopz/index.html",
    imageLink: "./Art/Flattopz/SlidingText.gif",
    author: "Flattopz",
    githubLink: "https://github.com/hjpunzalan",
  },
  {
    artName: "Rainbow Color Changer",
    pageLink: "./Art/mmshr/index.html",
    imageLink: "./Art/mmshr/rainbow.gif",
    author: "mmosehauer",
    githubLink: "https://github.com/mmosehauer",
  },
  {
    artName: "World of Coding",
    pageLink: "./Art/tom_kn/coding.html",
    imageLink: "./Art/tom_kn/coding.gif",
    author: "Tamas Knisz",
    githubLink: "https://github.com/TamasKn",
  },
  {
    artName: "Atom",
    pageLink: "./Art/Teva/index.html",
    imageLink: "./Art/Teva/atom.gif",
    author: "Teva",
    githubLink: "https://github.com/TevaHenry",
  },
  {
    artName: "Be Awesome",
    pageLink: "./Art/TigerAsH/index.html",
    imageLink: "./Art/TigerAsH/be-awesome.jpg",
    author: "TigerAsH",
    githubLink: "https://github.com/TigerAsH94",
  },
  {
    artName: "ZtM",
    pageLink: "./Art/thoyvo/index.html",
    imageLink: "./Art/thoyvo/ztm.gif",
    author: "Thoyvo",
    githubLink: "https://github.com/thoyvo",
  },
  {
    artName: "Fast Fishes",
    pageLink: "./Art/4ront/index.html",
    imageLink: "./Art/4ront/fishes.gif",
    author: "4rontender",
    githubLink: "https://github.com/RinatValiullov",
  },
  {
    artName: "Loading...",
    pageLink: "./Art/RedSquirrrel2/loading.html",
    imageLink: "./Art/RedSquirrrel2/loading.gif",
    author: "RedSquirrrel",
    githubLink: "https://github.com/RedSquirrrel",
  },
  {
    artName: "Animated Cube",
    pageLink: "./Art/Animated Cube/index.html",
    imageLink: "./Art/Animated Cube/cube.gif",
    author: "RedSquirrrel",
    githubLink: "https://github.com/RedSquirrrel",
  },
  {
    artName: "Calm Ubuntu",
    pageLink: "./Art/schupat/index.html",
    imageLink: "./Art/schupat/preview.gif",
    author: "schupat",
    githubLink: "https://github.com/schupat",
  },
  {
    artName: "Solar System",
    pageLink: "./Art/DSandberg93/index.html",
    imageLink: "./Art/DSandberg93/SolarSystem.gif",
    author: "DSandberg93",
    githubLink: "https://github.com/DSandberg93",
  },
  {
    artName: "Boo",
    pageLink: "./Art/VerityB/index.html",
    imageLink: "./Art/VerityB/boo.gif",
    author: "VerityB",
    githubLink: "https://github.com/VerityB",
  },
  {
    artName: "Hacktoberfest Ghost",
    pageLink: "./Art/cTahirih/index.html",
    imageLink: "./Art/cTahirih/ghost.png",
    author: "cTahirih",
    githubLink: "https://github.com/cTahirih",
  },
  {
    artName: "Clock",
    pageLink: "./Art/Abdul/index.html",
    imageLink: "./Art/Abdul/Clock.png",
    author: "Abdul Rahman",
    githubLink: "https://github.com/abdulrahman118",
  },
  {
    artName: "Loading Cube",
    pageLink: "./Art/andrearizzello/index.html",
    imageLink: "./Art/andrearizzello/index.gif",
    author: "Andrea Rizzello",
    githubLink: "https://github.com/andrearizzello",
  },
  {
    artName: "Wall Dropping Logo",
    pageLink: "./Art/shivams136/index.html",
    imageLink: "./Art/shivams136/walldrop.gif",
    author: "Shivam Sharma",
    githubLink: "https://github.com/ShivamS136",
  },
  {
    artName: "Infinite Race",
    pageLink: "./Art/levermanx/index.html",
    imageLink: "./Art/levermanx/anim.gif",
    author: "Levermanx",
    githubLink: "https://github.com/levermanx",
  },
  {
    artName: "Hover to Rotate Text",
    pageLink: "./Art/faiz_hameed/index.html",
    imageLink: "./Art/faiz_hameed/hackto.gif",
    author: "Faiz Hameed",
    githubLink: "https://github.com/faizhameed",
  },
  {
    artName: "Time goes by",
    pageLink: "./Art/WolfgangKreminger/index.html",
    imageLink: "./Art/WolfgangKreminger/showcase.gif",
    author: "Wolfgang Kreminger",
    githubLink: "https://github.com/r4pt0s",
  },
  {
    artName: "Simple Phone Animation",
    pageLink: "./Art/Lala/index.html",
    imageLink: "./Art/Lala/phone.gif",
    author: "Olamide Aboyeji",
    githubLink: "https://github.com/aolamide",
  },
  {
    artName: "Synthwave Sunset",
    pageLink: "./Art/brunobolting/index.html",
    imageLink: "./Art/brunobolting/synthwave-sunset.gif",
    author: "Bruno Bolting",
    githubLink: "https://github.com/brunobolting/",
  },
  {
    artName: "Kawaii Penguin",
    pageLink: "./Art/Brienyll/index.html",
    imageLink: "./Art/Brienyll/kawaiiPenguin.gif",
    author: "Brienyll",
    githubLink: "https://github.com/brienyll/",
  },
  {
    artName: "Happy Halloween",
    pageLink: "./Art/MatthewS/index.html",
    imageLink: "./Art/MatthewS/Spider.gif",
    author: "MatthewS",
    githubLink: "https://github.com/matthewstoddart/",
  },
  {
    artName: "Fan Art",
    pageLink: "./Art/m-perez33/index.html",
    imageLink: "./Art/m-perez33/cylon.gif",
    author: "Marcos Perez",
    githubLink: "https://github.com/m-perez33/",
  },
  {
    artName: "That Animation",
    pageLink: "./Art/MaKloudz/index.html",
    imageLink: "./Art/MaKloudz/dat-animation.gif",
    author: "Blessing Mutava",
    githubLink: "https://github.com/MaKloudz",
  },
  {
    artName: "abhishek9686",
    pageLink: "./Art/abhishek9686/index.html",
    imageLink: "./Art/abhishek9686/loading.gif",
    author: "abhishek9686",
    githubLink: "https://github.com/abhishek9686",
  },
  {
    artName: "Animating Pot",
    pageLink: "./Art/Somechandra/index.html",
    imageLink: "./Art/Somechandra/pot.gif",
    author: "Somechandra",
    githubLink: "https://github.com/somechandra",
  },
  {
    artName: "Circles Circling",
    pageLink: "./Art/pikktorr/index.html",
    imageLink: "./Art/pikktorr/circles.gif",
    author: "pikktorr",
    githubLink: "https://github.com/pikktorr",
  },
  {
    artName: "Glitchy Szn",
    pageLink: "./Art/premdav/index.html",
    imageLink: "./Art/premdav/screenshot.png",
    author: "premdav",
    githubLink: "https://github.com/premdav",
  },
  {
    artName: "ZeroToMastery",
    pageLink: "./Art/Vzneers/index.html",
    imageLink: "./Art/Vzneers/gifzeroloading.gif",
    author: "TrinhMinhHieu",
    githubLink: "https://github.com/trinhminhhieu",
  },
  {
    artName: "Spacecraft-landing",
    pageLink: "./Art/DDuplinszki/index.html",
    imageLink: "./Art/DDuplinszki/Spacecraft-landing.gif",
    author: "DDuplinszki",
    githubLink: "https://github.com/DDuplinszki",
  },
  {
    artName: "Hover-Scale",
    pageLink: "./Art/echowebid/index.html",
    imageLink: "./Art/echowebid/hover.gif",
    author: "echowebid",
    githubLink: "https://github.com/echowebid",
  },
  {
    artName: "Welcome HactoberFest",
    pageLink: "./Art/Dhaval/index.html",
    imageLink: "./Art/Dhaval/Welcome-Hacktoberfest.gif",
    author: "Dhaval Mehta",
    githubLink: "https://github.com/Dhaval1403",
  },
  {
    artName: "Aynonimation",
    pageLink: "./Art/Aynorica/aynorica.html",
    imageLink: "./Art/Aynorica/Aynonimation.png",
    author: "aynorica",
    githubLink: "https://github.com/aynorica",
  },
  {
    artName: "sun-to-moon",
    pageLink: "./Art/haider/index.html",
    imageLink: "./Art/haider/sun-moon.gif",
    author: "Haider",
    githubLink: "https://github.com/hyderumer",
  },
  {
    artName: "Loader Circle",
    pageLink: "./Art/beaps/index.html",
    imageLink: "./Art/beaps/loader-circle.gif",
    author: "beaps",
    githubLink: "https://github.com/beaps",
  },
  {
    artName: "Doors",
    pageLink: "./Art/pauliax/index.html",
    imageLink: "./Art/pauliax/doors.gif",
    author: "pauliax",
    githubLink: "https://github.com/pauliax",
  },
  {
    artName: "Clock with pendulum",
    pageLink: "./Art/Pankaj/index.html",
    imageLink: "./Art/Pankaj/Clock_with_pendulum.gif",
    author: "Pankaj",
    githubLink: "https://github.com/prime417",
  },
  {
    artName: "Loader Circle",
    pageLink: "./Art/beaps/index.html",
    imageLink: "./Art/beaps/loader-circle.gif",
    author: "beaps",
    githubLink: "https://github.com/beaps",
  },
  {
    artName: "Doors",
    pageLink: "./Art/pauliax/index.html",
    imageLink: "./Art/pauliax/doors.gif",
    author: "pauliax",
    githubLink: "https://github.com/pauliax",
  },
  {
    artName: "Loader Square",
    pageLink: "./Art/beaps2/square-loader.html",
    imageLink: "./Art/beaps2/square-loader.gif",
    author: "beaps",
    githubLink: "https://github.com/beaps",
  },
  {
    artName: "Running Text",
    pageLink: "./Art/DevinEkadeni/running-text.html",
    imageLink: "./Art/DevinEkadeni/running-text.gif",
    author: "Devin Ekadeni",
    githubLink: "https://github.com/devinekadeni",
  },
  {
    artName: "Mystical-Hacktoberfest",
    pageLink: "./Art/Wayne/index.html",
    imageLink:
      "./Art/Wayne/hacktoberfest - Google Chrome 09 Oct 2019 21_12_32.png",
    author: "Wayne Mac Mavis",
    githubLink: "https://github.com/WayneMacMavis",
  },
  {
    artName: "ZTM Logo Animation",
    pageLink: "./Art/bk987/index.html",
    imageLink: "./Art/bk987/preview.gif",
    author: "Bilal Khalid",
    githubLink: "https://github.com/bk987",
  },
  {
    artName: "Pong",
    pageLink: "./Art/Carls13/index.html",
    imageLink: "./Art/Carls13/pong.jpg",
    author: "Carlos Hernandez",
    githubLink: "https://github.com/Carls13",
  },
  {
    artName: "ZTM Animation",
    pageLink: "./Art/EricPuskas/index.html",
    imageLink: "./Art/EricPuskas/index.gif",
    author: "Eric Puskas",
    githubLink: "https://github.com/EricPuskas",
  },
  {
    artName: "LSD Rainbow Trip: Phase 1",
    pageLink: "./Art/AbsMechanik/index.html",
    imageLink: "./Art/AbsMechanik/AbsMechanik_Animation.gif",
    author: "AbsMechanik",
    githubLink: "https://github.com/AbsMechanik",
  },
  {
    artName: "space zoo",
    pageLink: "./Art/space_zoo/index.html",
    imageLink: "./Art/space_zoo/space_zoo.gif",
    author: "yuwenGithub",
    githubLink: "https://github.com/yuwenGithub",
  },
  {
    artName: "eyes",
    pageLink: "./Art/eyes/index.html",
    imageLink: "./Art/eyes/eyes.gif",
    author: "yuwenGithub",
    githubLink: "https://github.com/yuwenGithub",
  },
  {
    artName: "Spooktober Hacktoberfest",
    pageLink: "./Art/FredAmartey/index.html",
    imageLink: "./Art/FredAmartey/thumbnaill.gif",
    author: "Fred Amartey",
    githubLink: "https://github.com/FredAmartey",
  },
  {
    artName: "Star Wars?",
    pageLink: "./Art/henryvalbuena/index.html",
    imageLink: "./Art/henryvalbuena/index.gif",
    author: "Henry Valbuena",
    githubLink: "https://github.com/henryvalbuena",
  },
  {
    artName: "The Ripple",
    pageLink: "./Art/Anmol2/index.html",
    imageLink: "./Art/Anmol2/ripple.png",
    author: "Anmol",
    githubLink: "https://github.com/Anmol270900",
  },
  {
    artName: "Rainbow loader",
    pageLink: "./Art/ka-hn/rainbow.html",
    imageLink: "./Art/ka-hn/rainbow.gif",
    author: "Karim Hussain",
    githubLink: "https://github.com/ka-hn",
  },
  {
    artName: "The Sun",
    pageLink: "./Art/Anmol/index.html",
    imageLink: "./Art/Anmol/sun.png",
    author: "Anmol",
    githubLink: "https://github.com/Anmol270900",
  },
  {
    artName: "Flipbox",
    pageLink: "./Art/Prasheel/index.html",
    imageLink: "./Art/Prasheel/flip.gif",
    author: "Prasheel Soni",
    githubLink: "https://github.com/ps011",
  },
  {
    artName: "2019 Wave",
    pageLink: "./Art/chris-aqui/index.html",
    imageLink: "./Art/chris-aqui/2019-jump.gif",
    author: "Christine Aqui",
    githubLink: "https://github.com/christine-aqui",
  },
  {
    artName: "Hover Button Animation",
    pageLink: "./Art/Vipul/hover.html",
    imageLink: "./Art/Vipul/Screenshot2.png",
    author: "Vipul",
    githubLink: "https://github.com/vipuljain08",
  },
  {
    artName: "Start From Zero",
    pageLink: "./Art/Robihdy/index.html",
    imageLink: "./Art/Robihdy/start-from-zero.png",
    author: "Robihdy",
    githubLink: "https://github.com/Robihdy",
  },
  {
    artName: "Sliding Lines",
    pageLink: "./Art/erics0n/sliding-lines/index.html",
    imageLink: "./Art/erics0n/sliding-lines/image.gif",
    author: "erics0n",
    githubLink: "https://github.com/erics0n",
  },
  {
    artName: "Burger Menu",
    pageLink: "./Art/mctrl/burger.html",
    imageLink: "./Art/mctrl/burger.gif",
    author: "Martina",
    githubLink: "https://github.com/mctrl",
  },
  {
    artName: "Square Loader",
    pageLink: "./Art/Hemant/index.html",
    imageLink: "./Art/Hemant/loader.gif",
    author: "Hemant Garg",
    githubLink: "https://github.com/hemant-garg",
  },
  {
    artName: "wake up, neo...",
    pageLink: "./Art/samirjouni/TributeToTheMatrix.html",
    imageLink: "./Art/samirjouni/sample.gif",
    author: "Samir Jouni",
    githubLink: "https://github.com/samirjouni",
  },
  {
    artName: "Tribute To COD4MW",
    pageLink: "./Art/samirjouni2/index.html",
    imageLink: "./Art/samirjouni2/sample.gif",
    author: "Samir Jouni",
    githubLink: "https://github.com/samirjouni",
  },
  {
    artName: "Planet",
    pageLink: "./Art/ArthurDoom/planet.html",
    imageLink: "./Art/ArthurDoom/planet.gif",
    author: "ArthurDoom",
    githubLink: "https://github.com/ArthurDoom",
  },
  {
    artName: "SquarPy",
    pageLink: "./Art/Utkarsh/index.html",
    imageLink: "./Art/Utkarsh/hack.gif",
    author: "utkarsh",
    githubLink: "https://github.com/Utkarsh2604",
  },
  {
    artName: "Circle",
    pageLink: "./Art/Oliver/Circle.html",
    imageLink: "./Art/Oliver/circle.gif",
    author: "Oliver",
    githubLink: "https://github.com/oliver-gomes",
  },
  {
    artName: "Ellipse Loader",
    pageLink: "./Art/VaibhavKhulbe/EllipseLoader.html",
    imageLink: "./Art/VaibhavKhulbe/ellipseLoader.gif",
    author: "Vaibhav Khulbe",
    githubLink: "https://github.com/Kvaibhav01",
  },
  {
    artName: "Simple Loader",
    pageLink: "./Art/soumsps/simpleload.html",
    imageLink: "./Art/soumsps/sample.gif",
    author: "Soumendu Sinha",
    githubLink: "https://github.com/soumsps",
  },
  {
    artName: "Rollodex",
    pageLink: "./Art/Shruti/rolling.html",
    imageLink: "./Art/Shruti/rolling.gif",
    author: "Shruti",
    githubLink: "https://github.com/shruti49",
  },
  {
    artName: "Cute Cat",
    pageLink: "./Art/Alghi/cat.html",
    imageLink: "./Art/Alghi/cat.gif",
    author: "Alghi",
    githubLink: "https://github.com/darklordace",
  },
  {
    artName: "ZtM Text",
    pageLink: "./Art/Di4iMoRtAl/ZtM_text_animation.html",
    imageLink: "./Art/Di4iMoRtAl/ZtM_animation.gif",
    author: "Di4iMoRtAl",
    githubLink: "https://github.com/dppeykov",
  },
  {
    artName: "Circles",
    pageLink: "./Art/Bhuvana/circles.html",
    imageLink: "./Art/Bhuvana/circles.gif",
    author: "Bhuvana",
    githubLink: "https://github.com/bhuvana-guna",
  },
  {
    artName: "Bird",
    pageLink: "./Art/Bhuvana/bird.html",
    imageLink: "./Art/Bhuvana/bird.gif",
    author: "Bhuvana",
    githubLink: "https://github.com/bhuvana-guna",
  },
  {
    artName: "Loader",
    pageLink: "./Art/Bhuvana/loader.html",
    imageLink: "./Art/Bhuvana/loader.gif",
    author: "Bhuvana",
    githubLink: "https://github.com/bhuvana-guna",
  },
  {
    artName: "Css Pulse",
    pageLink: "./Art/Aszmel/pulse.html",
    imageLink: "./Art/Aszmel/css_pulse.gif",
    author: "Aszmel",
    githubLink: "https://github.com/Aszmel",
  },
  {
    artName: "Circle Bounce",
    pageLink: "./Art/Edmund/index.html",
    imageLink: "./Art/Edmund/circle-bounce.gif",
    author: "Edmund",
    githubLink: "https://github.com/edmund1645",
  },
  {
    artName: "Heart Beating",
    pageLink: "./Art/Regem/index.html",
    imageLink: "./Art/Regem/heart.jpg",
    author: "Regem",
    githubLink: "https://github.com/GemzBond",
  },
  {
    artName: "Fading Circles",
    pageLink: "./Art/Ankit/fadeCircle.html",
    imageLink: "./Art/Ankit/fadeCircles.png",
    author: "Ankit Srivastava",
    githubLink: "https://github.com/a18nov",
  },
  {
    artName: "Hacktoberfest 2019",
    pageLink: "./Art/jpk3lly/animation.html",
    imageLink: "./Art/jpk3lly/JPs_Animation_GIF.gif",
    author: "jpk3lly",
    githubLink: "https://github.com/jpk3lly",
  },
  {
    artName: "Name Rotator",
    pageLink: "./Art/Meet/name.html",
    imageLink: "./Art/Meet/name.gif",
    author: "Meet",
    githubLink: "https://github.com/Meet1103",
  },
  {
    artName: "Ball Rotator",
    pageLink: "./Art/Bibekpreet/index.html",
    imageLink: "./Art/Bibekpreet/ball.gif",
    author: "Bibekpreet",
    githubLink: "https://github.com/bibekpreet99",
  },
  {
    artName: "Loading",
    pageLink: "./Art/jh1992jh/loading.html",
    imageLink: "./Art/jh1992jh/loading.gif",
    author: "jh1992jh",
    githubLink: "https://github.com/jh1992jh",
  },
  {
    artName: "ZTM Colors",
    pageLink: "./Art/Godnon/index.html",
    imageLink: "./Art/Godnon/ZTMcAnim.gif",
    author: "Godnon",
    githubLink: "https://github.com/godnondsilva",
  },
  {
    artName: "Hover Effect",
    pageLink: "./Art/Shubhankar/index.html",
    imageLink: "./Art/Shubhankar/hackoctober.gif",
    author: "Shubhankar",
    githubLink: "https://github.com/shubhdwiv12",
  },
  {
    artName: "5 balls preloader",
    pageLink: "./Art/Nnaji-Victor/index.html",
    imageLink: "./Art/Nnaji-Victor/5_balls.gif",
    author: "Nnaji Victor",
    githubLink: "https://github.com/Nnaji-Victor",
  },
  {
    artName: "ZTM Bouncer",
    pageLink: "./Art/Josia/bouncer.html",
    imageLink: "./Art/Josia/ztmbouncer.gif",
    author: "Josia Rodriguez",
    githubLink: "https://github.com/josiarod",
  },
  {
    artName: "Hacktober loading animation",
    pageLink: "./Art/mehul1011/index.html",
    imageLink: "./Art/mehul1011/loading.gif",
    author: "Mehul1011",
    githubLink: "https://github.com/mehul1011",
  },
  {
    artName: "Loading Dots",
    pageLink: "./Art/devSergiu/index.html",
    imageLink: "./Art/devSergiu/loading.gif",
    author: "devSergiu",
    githubLink: "https://github.com/devsergiu",
  },
  {
    artName: "TypeWriter effect",
    pageLink: "./Art/Sidharth/Typing_Text.html",
    imageLink: "./Art/Sidharth/type_writer.gif",
    author: "Sidharth",
    githubLink: "https://github.com/Sidharth98",
  },
  {
    artName: "Blue Spin",
    pageLink: "./Art/JamesW/index.html",
    imageLink: "./Art/JamesW/hacktober_spin.gif",
    author: "James Whitney",
    githubLink: "https://github.com/jameswhitney",
  },
  {
    artName: "Loading Animation",
    pageLink: "./Art/Sidharth/Loading.html",
    imageLink: "./Art/Sidharth/Loading.gif",
    author: "Sidharth",
    githubLink: "https://github.com/Sidharth98",
  },
  {
    artName: "Rotation",
    pageLink: "./Art/alenanog/index.html",
    imageLink: "./Art/alenanog/rotation.gif",
    author: "Alena A.",
    githubLink: "https://github.com/alenanog",
  },
  {
    artName: "Colors in your life",
    pageLink: "./Art/Atipahy/colors.html",
    imageLink: "./Art/Atipahy/colors.png",
    author: "Christos Chr",
    githubLink: "https://github.com/atipaHy",
  },
  {
    artName: "Orb",
    pageLink: "./Art/Jkbicbic/orb.html",
    imageLink: "./Art/Jkbicbic/orb.gif",
    author: "John Kennedy Bicbic",
    githubLink: "https://github.com/jkbicbic",
  },
  {
    artName: "Charging...",
    pageLink: "./Art/Afraz/charging.html",
    imageLink: "./Art/Afraz/charging.gif",
    author: "Afraz",
    githubLink: "https://github.com/afrazz",
  },
  {
    artName: "Charging...",
    pageLink: "./Art/DepStep/depstep.html",
    imageLink: "./Art/DepStep/depstep.gif",
    author: "DepStep",
    githubLink: "https://github.com/stephD",
  },
  {
    artName: "Dancing Ball...",
    pageLink: "./Art/DaveFres/index.html",
    imageLink: "./Art/DaveFres/ball.gif",
    author: "DaveFres",
    githubLink: "https://github.com/DaveFres",
  },
  {
    artName: "Sunshine",
    pageLink: "./Art/Pavelisp/sunshine.html",
    imageLink: "./Art/Pavelisp/sunshine.gif",
    author: "Pavel Isp",
    githubLink: "https://github.com/pavelisp",
  },
  {
    artName: "Cheshire",
    pageLink: "./Art/Ckanelin/index.html",
    imageLink: "./Art/Ckanelin/Cheshire.gif",
    author: "Ckanelin",
    githubLink: "https://github.com/ckanelin",
  },
  {
    artName: "Disappear",
    pageLink: "./Art/Stacy/index.html",
    imageLink: "./Art/Stacy/disappear.gif",
    author: "Stacy",
    githubLink: "https://github.com/stacyholtz6",
  },
  {
    artName: "Ellipse Spinner",
    pageLink: "./Art/Sabina/ellipse_spinner.html",
    imageLink: "./Art/Sabina/ellipse_spinner.png",
    author: "Sabina Abbasova",
    githubLink: "https://github.com/sabina929",
  },
  {
    artName: "NightSky",
    pageLink: "./Art/AndyS/index.html",
    imageLink: "./Art/AndyS/Capture.GIF",
    author: "AndyS",
    githubLink: "https://github.com/AndyS1988",
  },
  {
    artName: "Hungry",
    pageLink: "./Art/diegchav/index.html",
    imageLink: "./Art/diegchav/hungry.gif",
    author: "Diego Chz",
    githubLink: "https://github.com/diegchav",
  },
  {
    artName: "Colorize",
    pageLink: "./Art/JimBratsos/colorize.html",
    imageLink: "./Art/JimBratsos/Colorize.gif",
    author: "Jim Bratsos",
    githubLink: "https://github.com/JimBratsos",
  },
  {
    artName: "Hacktober Spooktacular",
    pageLink: "Art/Elex/index.html",
    imageLink: ["./Art/Elex/hhs.gif"],
    author: "William Poisel (LordCobra)",
    githubLink: "https://github.com/epoisel",
  },
  {
    artName: "Circley",
    pageLink: "./Art/Tranjenny/indexjenny.html",
    imageLink: "./Art/Tranjenny/zerojenny.gif",
    author: "Tranjenny",
    githubLink: "https://github.com/Tranjenny",
  },
  {
    artName: "My Vietnam",
    pageLink: "./Art/nhbduy/index.html",
    imageLink: "./Art/nhbduy/my-vietnam.gif",
    author: "Hoang-Bao-Duy NGUYEN",
    githubLink: "https://github.com/nhbduy",
  },
  {
    artName: "Hactoberfest Bus",
    pageLink: "./Art/shahpranaf/index.html",
    imageLink: "./Art/shahpranaf/hacktoberfest_bus.gif",
    author: "Pranav Shah",
    githubLink: "https://github.com/shahpranaf",
  },
  {
    artName: "Hacktoberfest",
    pageLink: "./Art/robihid/index.html",
    imageLink: "./Art/robihid/hacktoberfest.png",
    author: "robihid",
    githubLink: "https://github.com/robihid",
  },
  {
    artName: "Hi there",
    pageLink: "./Art/Aki/index.html",
    imageLink: "./Art/Aki/giphy.gif",
    author: "Aki",
    githubLink: "https://github.com/akmalist",
  },
  {
    artName: "Hacktoberfest 2019!",
    pageLink: "./Art/RedSquirrrel/index.html",
    imageLink: "./Art/RedSquirrrel/index.html/animation.PNG",
    author: "RedSquirrrel",
    githubLink: "https://github.com/RedSquirrrel",
  },
  {
    artName: "Sliding text",
    pageLink: "./Art/Flattopz/index.html",
    imageLink: "./Art/Flattopz/SlidingText.gif",
    author: "Flattopz",
    githubLink: "https://github.com/hjpunzalan",
  },
  {
    artName: "Rainbow Color Changer",
    pageLink: "./Art/mmshr/index.html",
    imageLink: "./Art/mmshr/rainbow.gif",
    author: "mmosehauer",
    githubLink: "https://github.com/mmosehauer",
  },
  {
    artName: "World of Coding",
    pageLink: "./Art/tom_kn/coding.html",
    imageLink: "./Art/tom_kn/coding.gif",
    author: "Tamas Knisz",
    githubLink: "https://github.com/TamasKn",
  },
  {
    artName: "Atom",
    pageLink: "./Art/Teva/index.html",
    imageLink: "./Art/Teva/atom.gif",
    author: "Teva",
    githubLink: "https://github.com/TevaHenry",
  },
  {
    artName: "Be Awesome",
    pageLink: "./Art/TigerAsH/index.html",
    imageLink: "./Art/TigerAsH/be-awesome.jpg",
    author: "TigerAsH",
    githubLink: "https://github.com/TigerAsH94",
  },
  {
    artName: "ZtM",
    pageLink: "./Art/thoyvo/index.html",
    imageLink: "./Art/thoyvo/ztm.gif",
    author: "Thoyvo",
    githubLink: "https://github.com/thoyvo",
  },
  {
    artName: "Fast Fishes",
    pageLink: "./Art/4ront/index.html",
    imageLink: "./Art/4ront/fishes.gif",
    author: "4rontender",
    githubLink: "https://github.com/RinatValiullov",
  },
  {
    artName: "Loading...",
    pageLink: "./Art/RedSquirrrel2/loading.html",
    imageLink: "./Art/RedSquirrrel2/loading.gif",
    author: "RedSquirrrel",
    githubLink: "https://github.com/RedSquirrrel",
  },
  {
    artName: "Animated Cube",
    pageLink: "./Art/Animated Cube/index.html",
    imageLink: "./Art/Animated Cube/cube.gif",
    author: "RedSquirrrel",
    githubLink: "https://github.com/RedSquirrrel",
  },
  {
    artName: "Calm Ubuntu",
    pageLink: "./Art/schupat/index.html",
    imageLink: "./Art/schupat/preview.gif",
    author: "schupat",
    githubLink: "https://github.com/schupat",
  },
  {
    artName: "Solar System",
    pageLink: "./Art/DSandberg93/index.html",
    imageLink: "./Art/DSandberg93/SolarSystem.gif",
    author: "DSandberg93",
    githubLink: "https://github.com/DSandberg93",
  },
  {
    artName: "Boo",
    pageLink: "./Art/VerityB/index.html",
    imageLink: "./Art/VerityB/boo.gif",
    author: "VerityB",
    githubLink: "https://github.com/VerityB",
  },
  {
    artName: "Hacktoberfest Ghost",
    pageLink: "./Art/cTahirih/index.html",
    imageLink: "./Art/cTahirih/ghost.png",
    author: "cTahirih",
    githubLink: "https://github.com/cTahirih",
  },
  {
    artName: "Clock",
    pageLink: "./Art/Abdul/index.html",
    imageLink: "./Art/Abdul/Clock.png",
    author: "Abdul Rahman",
    githubLink: "https://github.com/abdulrahman118",
  },
  {
    artName: "Loading Cube",
    pageLink: "./Art/andrearizzello/index.html",
    imageLink: "./Art/andrearizzello/index.gif",
    author: "Andrea Rizzello",
    githubLink: "https://github.com/andrearizzello",
  },
  {
    artName: "Wall Dropping Logo",
    pageLink: "./Art/shivams136/index.html",
    imageLink: "./Art/shivams136/walldrop.gif",
    author: "Shivam Sharma",
    githubLink: "https://github.com/ShivamS136",
  },
  {
    artName: "Infinite Race",
    pageLink: "./Art/levermanx/index.html",
    imageLink: "./Art/levermanx/anim.gif",
    author: "Levermanx",
    githubLink: "https://github.com/levermanx",
  },
  {
    artName: "Hover to Rotate Text",
    pageLink: "./Art/faiz_hameed/index.html",
    imageLink: "./Art/faiz_hameed/hackto.gif",
    author: "Faiz Hameed",
    githubLink: "https://github.com/faizhameed",
  },
  {
    artName: "Time goes by",
    pageLink: "./Art/WolfgangKreminger/index.html",
    imageLink: "./Art/WolfgangKreminger/showcase.gif",
    author: "Wolfgang Kreminger",
    githubLink: "https://github.com/r4pt0s",
  },
  {
    artName: "Simple Phone Animation",
    pageLink: "./Art/Lala/index.html",
    imageLink: "./Art/Lala/phone.gif",
    author: "Olamide Aboyeji",
    githubLink: "https://github.com/aolamide",
  },
  {
    artName: "Synthwave Sunset",
    pageLink: "./Art/brunobolting/index.html",
    imageLink: "./Art/brunobolting/synthwave-sunset.gif",
    author: "Bruno Bolting",
    githubLink: "https://github.com/brunobolting/",
  },

  {
    artName: "Kawaii Penguin",
    pageLink: "./Art/Brienyll/index.html",
    imageLink: "./Art/Brienyll/kawaiiPenguin.gif",
    author: "Brienyll",
    githubLink: "https://github.com/brienyll/",
  },
  {
    artName: "Happy Halloween",
    pageLink: "./Art/MatthewS/index.html",
    imageLink: "./Art/MatthewS/Spider.gif",
    author: "MatthewS",
    githubLink: "https://github.com/matthewstoddart/",
  },
  {
    artName: "Fan Art",
    pageLink: "./Art/m-perez33/index.html",
    imageLink: "./Art/m-perez33/cylon.gif",
    author: "Marcos Perez",
    githubLink: "https://github.com/m-perez33/",
  },
  {
    artName: "Animating Pot",
    pageLink: "./Art/Somechandra/index.html",
    imageLink: "./Art/Somechandra/pot.gif",
    author: "Somechandra",
    githubLink: "https://github.com/somechandra",
  },
  {
    artName: "Circles Circling",
    pageLink: "./Art/pikktorr/index.html",
    imageLink: "./Art/pikktorr/circles.gif",
    author: "pikktorr",
    githubLink: "https://github.com/pikktorr",
  },
  {
    artName: "Glitchy Szn",
    pageLink: "./Art/premdav/index.html",
    imageLink: "./Art/premdav/screenshot.png",
    author: "premdav",
    githubLink: "https://github.com/premdav",
  },
  {
    artName: "ZeroToMastery",
    pageLink: "./Art/Vzneers/index.html",
    imageLink: "./Art/Vzneers/gifzeroloading.gif",
    author: "TrinhMinhHieu",
    githubLink: "https://github.com/trinhminhhieu",
  },
  {
    artName: "Spacecraft-landing",
    pageLink: "./Art/DDuplinszki/index.html",
    imageLink: "./Art/DDuplinszki/Spacecraft-landing.gif",
    author: "DDuplinszki",
    githubLink: "https://github.com/DDuplinszki",
  },
  {
    artName: "Hover-Scale",
    pageLink: "./Art/echowebid/index.html",
    imageLink: "./Art/echowebid/hover.gif",
    author: "echowebid",
    githubLink: "https://github.com/echowebid",
  },
  {
    artName: "Welcome HactoberFest",
    pageLink: "./Art/Dhaval/index.html",
    imageLink: "./Art/Dhaval/Welcome-Hacktoberfest.gif",
    author: "Dhaval Mehta",
    githubLink: "https://github.com/Dhaval1403",
  },
  {
    artName: "Aynonimation",
    pageLink: "./Art/Aynorica/aynorica.html",
    imageLink: "./Art/Aynorica/Aynonimation.png",
    author: "aynorica",
    githubLink: "https://github.com/aynorica",
  },
  {
    artName: "sun-to-moon",
    pageLink: "./Art/haider/index.html",
    imageLink: "./Art/haider/sun-moon.gif",
    author: "Haider",
    githubLink: "https://github.com/hyderumer",
  },
  {
    artName: "Loader Circle",
    pageLink: "./Art/beaps/index.html",
    imageLink: "./Art/beaps/loader-circle.gif",
    author: "beaps",
    githubLink: "https://github.com/beaps",
  },
  {
    artName: "Doors",
    pageLink: "./Art/pauliax/index.html",
    imageLink: "./Art/pauliax/doors.gif",
    author: "pauliax",
    githubLink: "https://github.com/pauliax",
  },
  {
    artName: "Clock with pendulum",
    pageLink: "./Art/Pankaj/index.html",
    imageLink: "./Art/Pankaj/Clock_with_pendulum.gif",
    author: "Pankaj",
    githubLink: "https://github.com/prime417",
  },
  {
    artName: "Loader Circle",
    pageLink: "./Art/beaps/index.html",
    imageLink: "./Art/beaps/loader-circle.gif",
    author: "beaps",
    githubLink: "https://github.com/beaps",
  },
  {
    artName: "Doors",
    pageLink: "./Art/pauliax/index.html",
    imageLink: "./Art/pauliax/doors.gif",
    author: "pauliax",
    githubLink: "https://github.com/pauliax",
  },
  {
    artName: "Loader Square",
    pageLink: "./Art/beaps2/square-loader.html",
    imageLink: "./Art/beaps2/square-loader.gif",
    author: "beaps",
    githubLink: "https://github.com/beaps",
  },
  {
    artName: "Running Text",
    pageLink: "./Art/DevinEkadeni/running-text.html",
    imageLink: "./Art/DevinEkadeni/running-text.gif",
    author: "Devin Ekadeni",
    githubLink: "https://github.com/devinekadeni",
  },
  {
    artName: "Mystical-Hacktoberfest",
    pageLink: "./Art/Wayne/index.html",
    imageLink:
      "./Art/Wayne/hacktoberfest - Google Chrome 09 Oct 2019 21_12_32.png",
    author: "Wayne Mac Mavis",
    githubLink: "https://github.com/WayneMacMavis",
  },
  {
    artName: "ZTM Logo Animation",
    pageLink: "./Art/bk987/index.html",
    imageLink: "./Art/bk987/preview.gif",
    author: "Bilal Khalid",
    githubLink: "https://github.com/bk987",
  },
  {
    artName: "Pong",
    pageLink: "./Art/Carls13/index.html",
    imageLink: "./Art/Carls13/pong.jpg",
    author: "Carlos Hernandez",
    githubLink: "https://github.com/Carls13",
  },
  {
    artName: "ZTM Reveal",
    pageLink: "./Art/bk987-2/index.html",
    imageLink: "./Art/bk987-2/preview.gif",
    author: "Bilal Khalid",
    githubLink: "https://github.com/bk987",
  },
  {
    artName: "Phone Greetings",
    pageLink: "./Art/ann-dev/index.html",
    imageLink: "./Art/ann-dev/screenshot.png",
    author: "ann-dev",
    githubLink: "https://github.com/ann-dev",
  },
  {
    artName: "Triangle Slide",
    pageLink: "./Art/grieff/index.html",
    imageLink: "./Art/grieff/triangle-animation.gif",
    author: "Grieff",
    githubLink: "https://github.com/grieff",
  },
  {
    artName: "Neon ZTM",
    pageLink: "./Art/grieff/text.html",
    imageLink: "./Art/grieff/neonZTM.gif",
    author: "Grieff",
    githubLink: "https://github.com/grieff",
  },
  {
    artName: "Flip Card",
    pageLink: "./Art/FlipCard/index.html",
    imageLink: "./Art/FlipCard/ezgif.com-video-to-gif.gif",
    author: "Saurabh",
    githubLink: "https://github.com/Saurabh-FullStackDev",
  },
  {
    artName: "Hacktoberfest Letter Popups",
    pageLink: "./Art/jmt3559/index.html",
    imageLink: "https://media.giphy.com/media/RKSRPGiIsy1f3Ji3j1/giphy.gif",
    author: "Juan T.",
    githubLink: "https://github.com/jmtellez",
  },
  {
    artName: "Oscillation",
    pageLink: "./Art/Oscillation/index.html",
    imageLink: "./Art/Oscillation/oscillation.gif",
    author: "Nandhakumar",
    githubLink: "https://github.com/Nandhakumar7792",
  },
  {
    artName: "Letters flipUp",
    pageLink: "./Art/TerenceBiney/index.html",
    imageLink: "./Art/TerenceBiney/lettersanimate.gif",
    author: "Terence Biney",
    githubLink: "https://github.com/Tereflech17",
  },
  {
    artName: "Colors rectangle",
    pageLink: "./Art/beaps3/index.html",
    imageLink: "./Art/beaps3/colors-rectangle.gif",
    author: "beaps",
    githubLink: "https://github.com/beaps",
  },
  {
    artName: "Hinge",
    pageLink: "./Art/hereisfahad/index.html",
    imageLink: "./Art/hereisfahad/hinge.png",
    author: "Hereisfahad",
    githubLink: "https://github.com/hereisfahad",
  },
  {
    artName: "Animation",
    pageLink: "./Art/PaulBillings/animation.html",
    imageLink: "./Art/PaulBillings/animation.gif",
    author: "Paul Billings",
    githubLink: "https://github.com/paulbillings",
  },
  {
    artName: "Diminishing",
    pageLink: "./Art/Diminishing/index.html",
    imageLink: "./Art/Diminishing/diminishing.gif",
    author: "Nandhakumar",
    githubLink: "https://github.com/Nandhakumar7792",
  },
  {
    artName: "yin-yang",
    pageLink: "./Art/yin-yang/index.html",
    imageLink: "./Art/yin-yang/yin-yang.gif",
    author: "Nandhakumar",
    githubLink: "https://github.com/Nandhakumar7792",
  },
  {
    artName: "eggJiggle",
    pageLink: "./Art/eggJiggle/index.html",
    imageLink: "./Art/eggJiggle/eggJiggle.gif",
    author: "Nandhakumar",
    githubLink: "https://github.com/Nandhakumar7792",
  },
  {
    artName: "Aynonimation",
    pageLink: "./Art/Aynorica/aynorica.html",
    imageLink: "./Art/Aynorica/Aynonimation.png",
    author: "aynorica",
    githubLink: "https://github.com/aynorica",
  },
  {
    artName: "Calm",
    pageLink: "./Art/TMax/index.html",
    imageLink: "./Art/TMax/Choas.gif",
    author: "Tanesha",
    githubLink: "https://github.com/Mainemirror",
  },
  {
    artName: "Eyes",
    pageLink: "./Art/Ltheory/main.html",
    imageLink: "./Art/Ltheory/eyes.gif",
    author: "Ltheory",
    githubLink: "https://github.com/Ltheory",
  },
  {
    artName: "Jelly!",
    pageLink: "./Art/Pete331/index.html",
    imageLink: "./Art/Pete331/jelly.png",
    author: "Pete331",
    githubLink: "https://github.com/Pete331",
  },
  {
    artName: "clock-animation",
    pageLink: "./Art/clock-animation/clock.html",
    imageLink: "./Art/clock-animation/clock.gif",
    author: "Alan sarluv",
    githubLink: "https://github.com/alansarluv",
  },
  {
    artName: "Slider",
    pageLink: "./Art/furqan/index.html",
    imageLink: "./Art/furqan/in.gif",
    author: "Furqan",
    githubLink: "https://github.com/furki911s",
  },
  {
    artName: "animated-birds",
    pageLink: "./Art/g-serban/animated-birds.html",
    imageLink: "./Art/g-serban/animated-birds.gif",
    author: "g-serban",
    githubLink: "https://github.com/g-serban",
  },
  {
    artName: "circle-become-square",
    pageLink: "./Art/chathura19/index.html",
    imageLink: "./Art/chathura19/chathura.gif",
    author: "Chathura Samarajeewa",
    githubLink: "https://github.com/ChathuraSam",
  },
  {
    artName: "page-flicker",
    pageLink: "./Art/neon-flights/page-flicker.html",
    imageLink: "./Art/neon-flights/page-flicker.gif",
    author: "neon-flights",
    githubLink: "https://github.com/neon-flights",
  },
  {
    artName: "Animate-Name",
    pageLink: "./Art/Natalina/index.html",
    imageLink: "./Art/Natalina/animatename.gif",
    author: "Natalina",
    githubLink: "https://github.com/Natalina13",
  },
  {
    artName: "Asteroids",
    pageLink: "./Art/hrafnkellbaldurs/index.html",
    imageLink: "./Art/hrafnkellbaldurs/asteroids.gif",
    author: "Hrafnkell Baldursson",
    githubLink: "https://github.com/hrafnkellbaldurs",
  },
  {
    artName: "Sliding-Paragraph",
    pageLink: "./Art/Prashant/index.html",
    imageLink: "./Art/Prashant/slidingparagraph.gif",
    author: "Prashant",
    githubLink: "https://github.com/Prashant2108",
  },
  {
    artName: "Rocket Ship",
    pageLink: "./Art/sdangoy/rocket-ship.html",
    imageLink: "./Art/sdangoy/Rocket-Ship-Animation.gif",
    author: "sdangoy",
    githubLink: "https://github.com/sdangoy",
  },
  {
    artName: "Spinner",
    pageLink: "./Art/Sayan/index.html",
    imageLink: "./Art/Sayan/spinner.gif",
    author: "ssayanm",
    githubLink: "https://github.com/ssayanm",
  },
  {
    artName: "swivel",
    pageLink: "./Art/tusharhanda/index.html",
    imageLink: "./Art/tusharhanda/gif.gif",
    author: "Tushar",
    githubLink: "https://github.com/tusharhanda",
  },
  {
    artName: "Hallows Eve",
    pageLink: "./Art/ShanClayton/hallowseve.html",
    imageLink: "./Art/ShanClayton/hallowhack.gif",
    author: "Shanaun Clayton",
    githubLink: "https://github.com/shanclayton",
  },
  {
    artName: "Contraption",
    pageLink: "./Art/Aravindh/contraption.html",
    imageLink: "./Art/Aravindh/contraption.gif",
    author: "Aravindh",
    githubLink: "https://github.com/Aravindh-SNR",
  },
  {
    artName: "Rings",
    pageLink: "./Art/Kuzmycz/rings.html",
    imageLink: "./Art/Kuzmycz/rings.gif",
    author: "Mark Kuzmycz",
    githubLink: "https://github.com/kuzmycz",
  },
  {
    artName: "Ghost",
    pageLink: "./Art/toserjude/index.html",
    imageLink: "./Art/toserjude/boo.JPG",
    author: "toserjude",
    githubLink: "https://github.com/toserjude",
  },
  {
    artName: "Gradient circle",
    pageLink: "./Art/brettl1991/index.html",
    imageLink: "./Art/brettl1991/animation.png",
    author: "Agnes Brettl",
    githubLink: "https://github.com/brettl1991",
  },
  {
    artName: "Bill Cipher",
    pageLink: "./Art/vitoriapena/index.html",
    imageLink: "./Art/vitoriapena/bill_cipher.gif",
    author: "Vitória Mendes",
    githubLink: "https://github.com/vitoriapena",
  },
  {
    artName: "Gradient circle",
    pageLink: "./Art/brettl1991/index.html",
    imageLink: "./Art/brettl1991/animation.png",
    author: "Agnes Brettl",
    githubLink: "https://github.com/brettl1991",
  },
  {
    artName: "Bill Cipher",
    pageLink: "./Art/vitoriapena/index.html",
    imageLink: "./Art/vitoriapena/bill_cipher.gif",
    author: "Vitória Mendes",
    githubLink: "https://github.com/vitoriapena",
  },
  {
    artName: "Dizzy",
    pageLink: "./Art/antinomy/index.html",
    imageLink: "./Art/antinomy/logo-spin.gif",
    author: "Antinomezco",
    githubLink: "https://github.com/antinomezco",
  },
  {
    artName: "bounce",
    pageLink: "./Art/bounce/index.html",
    imageLink: "./Art/bounce/bounce.gif",
    author: "leelacanlale",
    githubLink: "https://github.com/leelacanlale",
  },
  {
    artName: "Bubbles",
    pageLink: "./Art/bubbles/Bubbles.html",
    imageLink: "./Art/bubbles/buubles.png",
    author: "michal",
    githubLink: "https://github.com/michalAim",
  },
  {
    artName: "Bar Slide",
    pageLink: "./Art/MikeVedsted/index.html",
    imageLink: "./Art/MikeVedsted/barslide.png",
    author: "Mike Vedsted",
    githubLink: "https://github.com/MikeVedsted",
  },
  {
    artName: "Text Animation",
    pageLink: "./Art/Divya/index.html",
    imageLink: "./Art/Divya/screenshot.png",
    author: "Divya",
    githubLink: "https://github.com/DivyaPuri25",
  },
  {
    artName: "HacktoberFest-2019-Entry",
    pageLink: "./Art/nunocpnp/index.html",
    imageLink: "./Art/nunocpnp/sample_image.jpg",
    author: "Nuno Pereira",
    githubLink: "https://github.com/nunocpnp",
  },
  {
    artName: "HacktoberFest 2019",
    pageLink: "./Art/AbdussamadYisau/index.html",
    imageLink: "./Art/AbdussamadYisau/Screenshot.png",
    author: "Abdussamad Yisau",
    githubLink: "https://github.com/AbdussamadYisau",
  },
  {
    artName: "squareMagic",
    pageLink: "./Art/Rajnish-SquareMagic/index.html",
    imageLink: "./Art/Rajnish-SquareMagic/squareMagic.png",
    author: "Rajnish Kr Singh",
    githubLink: "https://github.com/RajnishKrSingh",
  },
  {
    artName: "Robodance",
    pageLink: "./Art/robodance/index.html",
    imageLink: "./Art/robodance/robodance.gif",
    author: "Thomas",
    githubLink: "https://github.com/mahlqvist",
  },
  {
    artName: "ZTM animation",
    pageLink: "./Art/ZTManimation/index.html",
    author: "damniha",
    imageLink: "./Art/ZTManimation/ZTM_animation.gif",
    githubLink: "https://github.com/damniha",
  },
  {
    artName: "Double Helix",
    pageLink: "./Art/KeenanNunesVaz/index.html",
    imageLink: "./Art/KeenanNunesVaz/double-helix.gif",
    author: "KeenanNV",
    githubLink: "https://github.com/KeenanNunesVaz",
  },
  {
    artName: "October",
    pageLink: "./Art/fprokofiev/index.html",
    imageLink: "./Art/fprokofiev/october.gif",
    author: "Fyodor Prokofiev",
    githubLink: "https://github.com/fprokofiev",
  },
  {
    artName: "Asterisk Formation",
    pageLink: "./Art/NorahJC/index.html",
    imageLink: "./Art/NorahJC/asterisk-formation.gif",
    author: "NorahJC",
    githubLink: "https://github.com/norahjc",
  },
  {
    artName: "Ghost Balls",
    pageLink: "./Art/ghostBalls/index.html",
    imageLink: "./Art/ghostBalls/balls.png",
    author: "Beatriz Delmiro",
    githubLink: "https://github.com/biadelmiro",
  },
  {
    artName: "Walking Guy",
    pageLink: "./Art/walking-guy/index.html",
    imageLink: "./Art/walking-guy/video_gif.gif",
    author: "Rahulkumar Jha",
    githubLink: "https://github.com/Rahul240499",
  },
  {
    artName: "Hover Neon Animation",
    pageLink: "./Art/edjunma/index.html",
    imageLink: "./Art/edjunma/ejm-neon.gif",
    author: "edjunma",
    githubLink: "https://github.com/edjunma",
  },
  {
    artName: "Last In First Out Animation",
    pageLink: "./Art/Stryker/index.html",
    imageLink: "./Art/Stryker/zero-to-mastery-lifo-animation.gif",
    author: "Stryker Stinnette",
    githubLink: "https://github.com/StrykerKent",
  },
  {
    artName: "Happy Diwali Animation",
    pageLink: "./Art/Apoorva/index.html",
    imageLink: "./Art/Apoorva/Screen.gif",
    author: "Apoorva",
    githubLink: "https://github.com/apoorvamohite",
  },
  {
    artName: "Smoky Text",
    pageLink: "./Art/smoky-text/index.html",
    imageLink: "./Art/smoky-text/smoky_text_gif.gif",
    author: "Rahulkumar Jha",
    githubLink: "https://github.com/Rahul240499",
  },
  {
    artName: "Rainbow and Clouds",
    pageLink: "./Art/rainbowclouds/index.html",
    imageLink: "./Art/rainbowclouds/rainbowclouds.gif",
    author: "isasimoo",
    githubLink: "https://github.com/isasimo",
  },
  {
    artName: "prashantM1",
    pageLink: "./Art/prashantM1/heart.html",
    imageLink: "./Art/prashantM1/heart.gif",
    author: "Prashant Maurya",
    githubLink: "https://github.com/prashantmaurya228",
  },
  {
    artName: "Phone Greetings",
    pageLink: "./Art/ann-dev/index.html",
    imageLink: "./Art/ann-dev/screenshot.png",
    author: "ann-dev",
    githubLink: "https://github.com/ann-dev",
  },
  {
    artName: "Triangle Slide",
    pageLink: "./Art/grieff/index.html",
    imageLink: "./Art/grieff/triangle-animation.gif",
    author: "Grieff",
    githubLink: "https://github.com/grieff",
  },
  {
    artName: "Neon ZTM",
    pageLink: "./Art/grieff/text.html",
    imageLink: "./Art/grieff/neonZTM.gif",
    author: "Grieff",
    githubLink: "https://github.com/grieff",
  },
  {
    artName: "Flip Card",
    pageLink: "./Art/FlipCard/index.html",
    imageLink: "./Art/FlipCard/ezgif.com-video-to-gif.gif",
    author: "Saurabh",
    githubLink: "https://github.com/Saurabh-FullStackDev",
  },
  {
    artName: "Hacktoberfest Letter Popups",
    pageLink: "./Art/jmt3559/index.html",
    imageLink: "https://media.giphy.com/media/RKSRPGiIsy1f3Ji3j1/giphy.gif",
    author: "Juan T.",
    githubLink: "https://github.com/jmtellez",
  },
  {
    artName: "Oscillation",
    pageLink: "./Art/Oscillation/index.html",
    imageLink: "./Art/Oscillation/oscillation.gif",
    author: "Nandhakumar",
    githubLink: "https://github.com/Nandhakumar7792",
  },
  {
    artName: "Letters flipUp",
    pageLink: "./Art/TerenceBiney/index.html",
    imageLink: "./Art/TerenceBiney/lettersanimate.gif",
    author: "Terence Biney",
    githubLink: "https://github.com/Tereflech17",
  },
  {
    artName: "Colors rectangle",
    pageLink: "./Art/beaps3/index.html",
    imageLink: "./Art/beaps3/colors-rectangle.gif",
    author: "beaps",
    githubLink: "https://github.com/beaps",
  },
  {
    artName: "Hinge",
    pageLink: "./Art/hereisfahad/index.html",
    imageLink: "./Art/hereisfahad/hinge.png",
    author: "Hereisfahad",
    githubLink: "https://github.com/hereisfahad",
  },
  {
    artName: "Animation",
    pageLink: "./Art/PaulBillings/animation.html",
    imageLink: "./Art/PaulBillings/animation.gif",
    author: "Paul Billings",
    githubLink: "https://github.com/paulbillings",
  },
  {
    artName: "Diminishing",
    pageLink: "./Art/Diminishing/index.html",
    imageLink: "./Art/Diminishing/diminishing.gif",
    author: "Nandhakumar",
    githubLink: "https://github.com/Nandhakumar7792",
  },
  {
    artName: "yin-yang",
    pageLink: "./Art/yin-yang/index.html",
    imageLink: "./Art/yin-yang/yin-yang.gif",
    author: "Nandhakumar",
    githubLink: "https://github.com/Nandhakumar7792",
  },
  {
    artName: "eggJiggle",
    pageLink: "./Art/eggJiggle/index.html",
    imageLink: "./Art/eggJiggle/eggJiggle.gif",
    author: "Nandhakumar",
    githubLink: "https://github.com/Nandhakumar7792",
  },
  {
    artName: "Aynonimation",
    pageLink: "./Art/Aynorica/aynorica.html",
    imageLink: "./Art/Aynorica/Aynonimation.png",
    author: "aynorica",
    githubLink: "https://github.com/aynorica",
  },
  {
    artName: "Calm",
    pageLink: "./Art/TMax/index.html",
    imageLink: "./Art/TMax/Choas.gif",
    author: "Tanesha",
    githubLink: "https://github.com/Mainemirror",
  },
  {
    artName: "Eyes",
    pageLink: "./Art/Ltheory/main.html",
    imageLink: "./Art/Ltheory/eyes.gif",
    author: "Ltheory",
    githubLink: "https://github.com/Ltheory",
  },
  {
    artName: "Jelly!",
    pageLink: "./Art/Pete331/index.html",
    imageLink: "./Art/Pete331/jelly.png",
    author: "Pete331",
    githubLink: "https://github.com/Pete331",
  },
  {
    artName: "clock-animation",
    pageLink: "./Art/clock-animation/clock.html",
    imageLink: "./Art/clock-animation/clock.gif",
    author: "Alan sarluv",
    githubLink: "https://github.com/alansarluv",
  },
  {
    artName: "Slider",
    pageLink: "./Art/furqan/index.html",
    imageLink: "./Art/furqan/in.gif",
    author: "Furqan",
    githubLink: "https://github.com/furki911s",
  },
  {
    artName: "animated-birds",
    pageLink: "./Art/g-serban/animated-birds.html",
    imageLink: "./Art/g-serban/animated-birds.gif",
    author: "g-serban",
    githubLink: "https://github.com/g-serban",
  },
  {
    artName: "circle-become-square",
    pageLink: "./Art/chathura19/index.html",
    imageLink: "./Art/chathura19/chathura.gif",
    author: "Chathura Samarajeewa",
    githubLink: "https://github.com/ChathuraSam",
  },
  {
    artName: "page-flicker",
    pageLink: "./Art/neon-flights/page-flicker.html",
    imageLink: "./Art/neon-flights/page-flicker.gif",
    author: "neon-flights",
    githubLink: "https://github.com/neon-flights",
  },
  {
    artName: "Animate-Name",
    pageLink: "./Art/Natalina/index.html",
    imageLink: "./Art/Natalina/animatename.gif",
    author: "Natalina",
    githubLink: "https://github.com/Natalina13",
  },
  {
    artName: "Asteroids",
    pageLink: "./Art/hrafnkellbaldurs/index.html",
    imageLink: "./Art/hrafnkellbaldurs/asteroids.gif",
    author: "Hrafnkell Baldursson",
    githubLink: "https://github.com/hrafnkellbaldurs",
  },
  {
    artName: "Sliding-Paragraph",
    pageLink: "./Art/Prashant/index.html",
    imageLink: "./Art/Prashant/slidingparagraph.gif",
    author: "Prashant",
    githubLink: "https://github.com/Prashant2108",
  },
  {
    artName: "Rocket Ship",
    pageLink: "./Art/sdangoy/rocket-ship.html",
    imageLink: "./Art/sdangoy/Rocket-Ship-Animation.gif",
    author: "sdangoy",
    githubLink: "https://github.com/sdangoy",
  },
  {
    artName: "Spinner",
    pageLink: "./Art/Sayan/index.html",
    imageLink: "./Art/Sayan/spinner.gif",
    author: "ssayanm",
    githubLink: "https://github.com/ssayanm",
  },
  {
    artName: "swivel",
    pageLink: "./Art/tusharhanda/index.html",
    imageLink: "./Art/tusharhanda/gif.gif",
    author: "Tushar",
    githubLink: "https://github.com/tusharhanda",
  },
  {
    artName: "Hallows Eve",
    pageLink: "./Art/ShanClayton/hallowseve.html",
    imageLink: "./Art/ShanClayton/hallowhack.gif",
    author: "Shanaun Clayton",
    githubLink: "https://github.com/shanclayton",
  },
  {
    artName: "Contraption",
    pageLink: "./Art/Aravindh/contraption.html",
    imageLink: "./Art/Aravindh/contraption.gif",
    author: "Aravindh",
    githubLink: "https://github.com/Aravindh-SNR",
  },
  {
    artName: "Rings",
    pageLink: "./Art/Kuzmycz/rings.html",
    imageLink: "./Art/Kuzmycz/rings.gif",
    author: "Mark Kuzmycz",
    githubLink: "https://github.com/kuzmycz",
  },
  {
    artName: "Ghost",
    pageLink: "./Art/toserjude/index.html",
    imageLink: "./Art/toserjude/boo.JPG",
    author: "toserjude",
    githubLink: "https://github.com/toserjude",
  },
  {
    artName: "Gradient circle",
    pageLink: "./Art/brettl1991/index.html",
    imageLink: "./Art/brettl1991/animation.png",
    author: "Agnes Brettl",
    githubLink: "https://github.com/brettl1991",
  },
  {
    artName: "Bill Cipher",
    pageLink: "./Art/vitoriapena/index.html",
    imageLink: "./Art/vitoriapena/bill_cipher.gif",
    author: "Vitória Mendes",
    githubLink: "https://github.com/vitoriapena",
  },
  {
    artName: "Gradient circle",
    pageLink: "./Art/brettl1991/index.html",
    imageLink: "./Art/brettl1991/animation.png",
    author: "Agnes Brettl",
    githubLink: "https://github.com/brettl1991",
  },
  {
    artName: "Bill Cipher",
    pageLink: "./Art/vitoriapena/index.html",
    imageLink: "./Art/vitoriapena/bill_cipher.gif",
    author: "Vitória Mendes",
    githubLink: "https://github.com/vitoriapena",
  },
  {
    artName: "Dizzy",
    pageLink: "./Art/antinomy/index.html",
    imageLink: "./Art/antinomy/logo-spin.gif",
    author: "Antinomezco",
    githubLink: "https://github.com/antinomezco",
  },
  {
    artName: "bounce",
    pageLink: "./Art/bounce/index.html",
    imageLink: "./Art/bounce/bounce.gif",
    author: "leelacanlale",
    githubLink: "https://github.com/leelacanlale",
  },
  {
    artName: "Bubbles",
    pageLink: "./Art/bubbles/Bubbles.html",
    imageLink: "./Art/bubbles/buubles.png",
    author: "michal",
    githubLink: "https://github.com/michalAim",
  },
  {
    artName: "Bar Slide",
    pageLink: "./Art/MikeVedsted/index.html",
    imageLink: "./Art/MikeVedsted/barslide.png",
    author: "Mike Vedsted",
    githubLink: "https://github.com/MikeVedsted",
  },
  {
    artName: "Text Animation",
    pageLink: "./Art/Divya/index.html",
    imageLink: "./Art/Divya/screenshot.png",
    author: "Divya",
    githubLink: "https://github.com/DivyaPuri25",
  },
  {
    artName: "HacktoberFest-2019-Entry",
    pageLink: "./Art/nunocpnp/index.html",
    imageLink: "./Art/nunocpnp/sample_image.jpg",
    author: "Nuno Pereira",
    githubLink: "https://github.com/nunocpnp",
  },
  {
    artName: "HacktoberFest 2019",
    pageLink: "./Art/AbdussamadYisau/index.html",
    imageLink: "./Art/AbdussamadYisau/Screenshot.png",
    author: "Abdussamad Yisau",
    githubLink: "https://github.com/AbdussamadYisau",
  },
  {
    artName: "squareMagic",
    pageLink: "./Art/Rajnish-SquareMagic/index.html",
    imageLink: "./Art/Rajnish-SquareMagic/squareMagic.png",
    author: "Rajnish Kr Singh",
    githubLink: "https://github.com/RajnishKrSingh",
  },
  {
    artName: "Robodance",
    pageLink: "./Art/robodance/index.html",
    imageLink: "./Art/robodance/robodance.gif",
    author: "Thomas",
    githubLink: "https://github.com/mahlqvist",
  },
  {
    artName: "Sliding hacktober",
    pageLink: "./Art/Atif3/index.html",
    imageLink: "./Art/Atif3/sliding hacktober.gif",
    author: "Atif Iqbal",
    githubLink: "https://github.com/atif-dev",
  },
  {
    artName: "ZTM animation",
    pageLink: "./Art/ZTManimation/index.html",
    author: "damniha",
    imageLink: "./Art/ZTManimation/ZTM_animation.gif",
    githubLink: "https://github.com/damniha",
  },
  {
    artName: "Double Helix",
    pageLink: "./Art/KeenanNunesVaz/index.html",
    imageLink: "./Art/KeenanNunesVaz/double-helix.gif",
    author: "KeenanNV",
    githubLink: "https://github.com/KeenanNunesVaz",
  },
  {
    artName: "October",
    pageLink: "./Art/fprokofiev/index.html",
    imageLink: "./Art/fprokofiev/october.gif",
    author: "Fyodor Prokofiev",
    githubLink: "https://github.com/fprokofiev",
  },
  {
    artName: "Asterisk Formation",
    pageLink: "./Art/NorahJC/index.html",
    imageLink: "./Art/NorahJC/asterisk-formation.gif",
    author: "NorahJC",
    githubLink: "https://github.com/norahjc",
  },
  {
    artName: "Ghost Balls",
    pageLink: "./Art/ghostBalls/index.html",
    imageLink: "./Art/ghostBalls/balls.png",
    author: "Beatriz Delmiro",
    githubLink: "https://github.com/biadelmiro",
  },
  {
    artName: "Walking Guy",
    pageLink: "./Art/walking-guy/index.html",
    imageLink: "./Art/walking-guy/video_gif.gif",
    author: "Rahulkumar Jha",
    githubLink: "https://github.com/Rahul240499",
  },
  {
    artName: "Hover Neon Animation",
    pageLink: "./Art/edjunma/index.html",
    imageLink: "./Art/edjunma/ejm-neon.gif",
    author: "edjunma",
    githubLink: "https://github.com/edjunma",
  },
  {
    artName: "Last In First Out Animation",
    pageLink: "./Art/Stryker/index.html",
    imageLink: "./Art/Stryker/zero-to-mastery-lifo-animation.gif",
    author: "Stryker Stinnette",
    githubLink: "https://github.com/StrykerKent",
  },
  {
    artName: "Happy Diwali Animation",
    pageLink: "./Art/Apoorva/index.html",
    imageLink: "./Art/Apoorva/Screen.gif",
    author: "Apoorva",
    githubLink: "https://github.com/apoorvamohite",
  },
  {
    artName: "Smoky Text",
    pageLink: "./Art/smoky-text/index.html",
    imageLink: "./Art/smoky-text/smoky_text_gif.gif",
    author: "Rahulkumar Jha",
    githubLink: "https://github.com/Rahul240499",
  },
  {
    artName: "Rainbow and Clouds",
    pageLink: "./Art/rainbowclouds/index.html",
    imageLink: "./Art/rainbowclouds/rainbowclouds.gif",
    author: "isasimoo",
    githubLink: "https://github.com/isasimo",
  },
  {
    artName: "prashantM1",
    pageLink: "./Art/prashantM1/heart.html",
    imageLink: "./Art/prashantM1/heart.gif",
    author: "Prashant Maurya",
    githubLink: "https://github.com/prashantmaurya228",
  },

  {
    artName: "prashantM2",
    pageLink: "./Art/prashantM2/block.html",
    imageLink: "./Art/prashantM2/block.gif",
    author: "Prashant Maurya",
    githubLink: "https://github.com/prashantmaurya228",
  },
  {
    pageLink: "./Art/AnimationPandey/Index.html",
    imageLink: "./Art/AnimationPandey/Card.png",
    author: "Anish",
    githubLink: "https://github.com/apandey208",
  },
  {
    pageLink: "./Art/tfernandez2017/index.html",
    imageLink: "./Art/tfernandez2017/tfernandez2017.gif",
    author: "tfernandez2017",
    githubLink: "https://github.com/tfernandez2017",
  },
  {
    artName: "FlipSwap",
    pageLink: "./Art/Dadpops/index.html",
    imageLink: "./Art/Dadpops/anima.gif",
    author: "Chris",
    githubLink: "https://github.com/dadpops",
  },
  {
    artName: "Ufo Object",
    pageLink: "./Art/AndriusAlimas/index.html",
    imageLink: "./Art/AndriusAlimas/Ufo.gif",
    author: "Andrius Alimas",
    githubLink: "https://github.com/AndriusAlimas",
  },
  {
    artName: "Morph",
    pageLink: "./Art/Morph/index.html",
    imageLink: "./Art/Morph/Spread.gif",
    author: "Imiebo Godson",
    githubLink: "https://github.com/ImieboGodson",
  },
  {
    artName: "Waving-Penguin",
    pageLink: "./Art/waving-penguin/index.html",
    imageLink: "./Art/waving-penguin/image.png",
    author: "Sabyasachi Das",
    githubLink: "https://github.com/sabya2301",
  },
  {
    artName: "Colorful Circles",
    pageLink: "./Art/tuneer/index.html",
    imageLink: "./Art/tuneer/ss.png",
    author: "tuneer",
    githubLink: "https://github.com/tun-eer",
  },
  {
    artName: "Shuan",
    pageLink: "./Art/Raksha/index.html",
    imageLink: "./Art/Raksha/shaun.png",
    author: "Raksha Gupta",
    githubLink: "https://github.com/Raksha25",
  },
  {
    artName: "Chai_lover",
    pageLink: "./Art/Chai_lover/chai_lover.html",
    imageLink: "./Art/Chai_lover/Chai_lover.png",
    author: "Vivek2509",
    githubLink: "https://github.com/Vivek2509",
  },
  {
    artName: "Face",
    pageLink: "./Art/rashidmakki/index.html",
    imageLink: "./Art/rashidmakki/face.png",
    author: "Rashid Makki",
    githubLink: "https://github.com/rashidmakki",
  },
  {
    artName: "Wave",
    pageLink: "./Art/GabrielTeixeiraC/index.html",
    imageLink: "./Art/GabrielTeixeiraC/wave.png",
    author: "Gabriel Teixeira",
    githubLink: "https://github.com/GabrielTeixeiraC",
  },
  {
    artName: "Metal Hand",
    pageLink: "./Art/MetalHand/index.html",
    imageLink: "./Art/MetalHand/metal.png",
    author: "Adiyat",
    githubLink: "https://github.com/adiyatzzz",
  },
  {
    artName: "It's so cool",
    pageLink: "../Art/Abhishekalbert/index.html",
    imageLink: "../Art/Abhishekalbert/imageart.png",
    author: "Abhishek Kumar Shukla",
    githubLink: "https://github.com/abhishekalbert",
  },
  {
    artName: "Glow card",
    pageLink: "./Art/Glow-card/index.html",
    imageLink: "./Art/Glow-card/glowCard.png",
    author: "Wimansha Herath",
    githubLink: "https://github.com/wimanshaherath",
  },
  {
    artName: "Ferry",
    pageLink: "./Art/Ferry/index.html",
    imageLink: "./Art/Ferry/ferry.png",
    author: "AC",
    githubLink: "https://github.com/acphil2",
  },
  {
    artName: "Snail!",
    pageLink: "./Art/panvicka/index.html",
    imageLink: "./Art/panvicka/screen_gif.gif",
    author: "panvicka",
    githubLink: "https://github.com/panvicka",
  },
  {
    artName: "Spoopy",
    pageLink: "./Art/KccbzZ/index.html",
    imageLink: "./Art/KccbzZ/cover.png",
    author: "KccbzZ",
    githubLink: "https://github.com/KccbzZ/spoopy",
  },
  {
    artName: "Late Night Drive",
    pageLink: "./Art/KccbzZ/index.html",
    imageLink: "./Art/KccbzZ/cover.png",
    author: "KccbzZ",
    githubLink: "https://kccbzz.github.io/car/",
  },
  {
    artName: "Cool Buttons",
    pageLink: "./Art/PareshWadhwani/index.html",
    imageLink: "./Art/PareshWadhwani/Cool-Buttons.gif",
    author: "Paresh Wadhwani",
    githubLink: "https://github.com/parresh77",
  },
  {
    artName: "Bread Slicing",
    pageLink: "./Art/KccbzZ/index.html",
    imageLink: "./Art/KccbzZ/cover.png",
    author: "KccbzZ",
    githubLink: "https://kccbzz.github.io/cutting-bread-loading-screen/",
  },
  {
    artName: "ZTM_Logo",
    pageLink: "./Art/ZTM_Logo/index.html",
    imageLink: "./Art/ZTM_Logo/ZTM_logo.jpg",
    author: "Eder",
    githubLink: "https://github.com/EderIRE",
  },
 {
    artName: "Nisarga Gotekar Clock",
    pageLink: " ",
    imageLink: " ",
    author: "Nisarga",
    githubLink: "https://github.com/nisargagotekar",
  },
  {
    artName: "Bones",
    pageLink: "./Art/Bones/index.html",
    imageLink: "./Art/Bones/TrafficLight.PNG",
    author: "Philip",
    githubLink: "https://github.com/PhilipK-webdev",
  },
  {
    artName: "cherry",
    pageLink: "./Art/EyeOfAthena/index.html",
    imageLink: "./Art/EyeOfAthena/cover.png",
    author: "EyeOfAthena",
    githubLink: "https://github.com/EyeOfAthena/cherry",
  },
  {
    artName: "Breathe",
    pageLink: "./Art/breathe/index.html",
    imageLink: "./Art/breathe/breathegif.gif",
    author: "Casey",
    githubLink: "https://github.com/caseyferrara",
  },
  {
    artName: "irosco",
    pageLink: "./Art/Irosco/index.html",
    imageLink: "./Art/Irosco/Iroro.gif",
    author: "Irhose",
    githubLink: "https://github.com/Irhose",
  },
  {
    artName: "Mets_Bouncing_Logo",
    pageLink: "./Art/JoseAReinoso/index.html",
    imageLink: "./Art/JoseAReinoso/bouncingMets.GIF",
    author: "JoseAReinoso",
    githubLink: "https://github.com/JoseAReinoso",
  },
  {
    artName: "Rachies_1st_Contribution",
    pageLink: "./Art/Rachel/index.html",
    imageLink: "./Art/rainbow.png",
    author: "Rachel-Anna",
    githubLink: "https://github.com/Rachel-Anna",
  },
  {
    artName: "animBanner",
    pageLink: "./Art/animBanner/index.html",
    imageLink: "./Art/shinelikeasmile/animBanner.gif",
    author: "coolphynix",
    githubLink: "https://github.com/coolphynix",
  },
  {
    artName: "Jos02378 Logo",
    pageLink: "./Art/Jos02378/index.html",
    imageLink: "./Art/Jos02378/jos02378.png",
    author: "Jos02378",
    githubLink: "https://github.com/Jos02378",
  },
  {
    artName: "Responsible Emoji",
    pageLink: "./Art/PoojaSingh/index.html",
    imageLink: "./Art/PoojaSingh/responsible_emoji.png",
    author: "Pooja Singh",
    githubLink: "https://github.com/PSpooja",
  },
  {
    artName: "Happy Sun",
    pageLink: "./Art/kyloRen/index.html",
    imageLink: "./Art/kyloRen/kyloRen.gif",
    author: "Rohit",
    githubLink: "https://github.com/ghoshrohit72",
  },
  {
    artName: "Heartbeat",
    pageLink: "./Art/Devansh/index.html",
    imageLink: "./Art/Devanhs/heartbeatanim.gif",
    author: "Devansh",
    githubLink: "https://github.com/Devanshkr",
  },
  {
    artName: "updated CLock",
    pageLink: "./contribute-folder/index.html",
    imageLink: "./contribute-folder/Image_8",
    author: "Ishaan",
    githubLink: "https://github.com/ishaan14112000/",
  },
  {
    artName: "robot",
    pageLink: "./Art/18BIT0387/index.html",
    imageLink: "",
    author: "Aravind",
    githubLink: "https://github.com/aravindvrajeev",
  },
  {
    artName: "Rocket ship",
    pageLink: "./Art/Rocket_ship/index.html",
    imageLink: "./Art/Rocket_ship/Rocket-Ship.gif",
    author: "Gutu Galuppo",
    githubLink: "https://github.com/gutugaluppo",
  },
  {
    pageLink: './Art/AlexWNash/index.html',
    imageLink: './Art/AlexWNash/icon.gif',
    author: 'Alex Nash',
    githubLink: 'https://github.com/AlexWNash'
  },
  {
    artName: "Serious Monkey",
    pageLink: "./Art/bryguy/index1.html",
    imageLink: "./Art/bryguy/SeriousMonkeyCSS.gif",
    author: "Bryan Tellefsen",
    githubLink: "https://github.com/BTellefsen11",
  },{
    artName: "Seesaw",
    pageLink: "./Art/mariusz79/index.html",
    imageLink: "./Art/mariusz79/seesaw.png",
    author: "mariusz79",
    githubLink: "https://github.com/mariusz79",
  },{
    artName: "OCEAN",
    pageLink: "./Art/OCEAN/index.html",
    imageLink: "./Art/OCEAN/OCEAN.gif",
    author: "wordssaysalot",
    githubLink: "https://github.com/wordssaysalot",
  },{
    artName: "Stars",
    pageLink: "./Art/Atharva B/index.html",
    imageLink: "./Art/Atharva B/OCEAN.gif",
    author: "Attu",
    githubLink: "https://github.com/Atharva12Bowlekar",
  }
];

// +--------------------------------------------------------------------------------+
// +                                                                                +
// +                  YOU DO NOT NEED TO CHANGE ANYTHING BELOW THIS                 +
// +                                                                                +
// +--------------------------------------------------------------------------------+

// Creates cards from the array above
// You don't need to modify this
let contents = [];
Shuffle(cards).forEach((c) => {
  contents.push([
    `<li class="card">` +
      `<img class="art-image" src='${c.imageLink}' alt='${c.artName}' />` +
      `</a>` +
      `<div class="flex-content">` +
      `<a href='${c.pageLink}'><h3 class="art-title">${c.artName}</h3></a>` +
      `<p class='author'><a href="${c.githubLink}" target="_blank"><i class="fab fa-github"></i> ${c.author}</a> </p>` +
      `</div>` +
      `</li>`,
  ]);
});

document.getElementById("cards").innerHTML = contents;

function Shuffle(o) {
  for (
    var j, x, i = o.length;
    i;
    j = parseInt(Math.random() * i), x = o[--i], o[i] = o[j], o[j] = x
  );
  return o;
}
